# Generated by Django 2.1.8 on 2020-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimail', '0008_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedmessage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='messages', to='apimail.UserTag'),
        ),
    ]
