# Generated by Django 2.1.8 on 2020-01-31 08:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("apimail", "0012_composedmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComposedMessageAPIResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "response",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_responses",
                        to="apimail.ComposedMessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-datetime"],
            },
        ),
    ]
