# Generated by Django 2.1.8 on 2020-02-06 07:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apimail", "0017_auto_20200206_0554"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachmentfile",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
