# Generated by Django 2.1.8 on 2020-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apimail", "0018_attachmentfile_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composedmessage",
            name="body_text",
            field=models.TextField(blank=True),
        ),
    ]
