# Generated by Django 2.2.16 on 2020-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apimail", "0022_auto_20201017_1018"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=16,
            ),
        ),
    ]
