# Generated by Django 2.2.16 on 2020-10-17 14:58

import apimail.storage
import apimail.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apimail", "0023_domain_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentfile",
            name="file",
            field=models.FileField(
                storage=apimail.storage.APIMailSecureFileStorage(),
                upload_to="uploads/mail/attachments/%Y/%m/%d/",
                validators=[apimail.validators.validate_max_email_attachment_file_size],
            ),
        ),
    ]
