# Generated by Django 2.2.16 on 2020-10-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apimail", "0027_addressbookentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composedmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="composedmessage",
            name="to_recipient",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
