# Generated by Django 4.2.10 on 2024-03-14 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apimail", "0032_auto_20210716_0926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedmessage",
            name="read_by",
            field=models.ManyToManyField(
                blank=True, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
