# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20171229_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionuser',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
