# Generated by Django 3.2.18 on 2023-08-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_productionstream_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstream',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
