# Generated by Django 3.2.18 on 2023-10-06 15:27

from django.db import migrations, models
import django.utils.timezone


def log_type_value_to_key(apps, schema_editor):
    """
    Update WorkLog entries to use log_type keys instead of display values.
    """
    WorkLog = apps.get_model("finances", "WorkLog")
    from production.constants import WORK_LOG_TYPE_CHOICES

    for log_type, log_type_display in WORK_LOG_TYPE_CHOICES:
        # Update entries using the display value to use the log_type (key) value
        WorkLog.objects.filter(log_type__icontains=log_type_display).update(
            log_type=log_type
        )


def log_type_key_to_value(apps, schema_editor):
    """
    Reverse the log_type_value_to_key operation by reverting log_type values back to their display names.
    """
    WorkLog = apps.get_model("finances", "WorkLog")
    from production.constants import WORK_LOG_TYPE_CHOICES

    for log_type, log_type_display in WORK_LOG_TYPE_CHOICES:
        # Revert entries using the log_type (key) value back to the display value
        WorkLog.objects.filter(log_type=log_type).update(log_type=log_type_display)


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0010_alter_productionstream_opened"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionstream",
            name="opened",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(log_type_value_to_key, log_type_key_to_value),
    ]
