# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0045_auto_20170925_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('open_for_submission', models.BooleanField(default=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Journal')),
            ],
        ),
    ]
