# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scipost.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('journals', '0046_auto_20171019_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceedings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_activity', scipost.db.fields.AutoDateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('issue_name', models.CharField(max_length=256)),
                ('event_name', models.CharField(blank=True, max_length=256)),
                ('event_description', models.TextField(blank=True)),
                ('event_start_date', models.DateField(blank=True, null=True)),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('submissions_open', models.DateField()),
                ('submissions_deadline', models.DateField()),
                ('submissions_close', models.DateField()),
                ('fellowships', models.ManyToManyField(blank=True, related_name='proceedings', to='colleges.Fellowship')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings', to='journals.Issue')),
                ('lead_fellow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='colleges.Fellowship')),
            ],
            options={
                'verbose_name': 'Proceedings',
                'verbose_name_plural': 'Proceedings',
                'default_related_name': 'proceedings',
            },
        ),
    ]
