# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scipost.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_fellowship_guest'),
        ('proceedings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceeding',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proceeding',
            name='fellowships',
            field=models.ManyToManyField(blank=True, related_name='proceedings', to='colleges.Fellowship'),
        ),
        migrations.AddField(
            model_name='proceeding',
            name='latest_activity',
            field=scipost.db.fields.AutoDateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings', to='journals.Journal'),
        ),
    ]
