# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0002_remove_proceedings_issue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceedings',
            name='event_suffix',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
