# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0046_auto_20171019_1942'),
        ('proceedings', '0002_auto_20171015_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceeding',
            old_name='name',
            new_name='issue_name',
        ),
        migrations.RemoveField(
            model_name='proceeding',
            name='journal',
        ),
        migrations.AddField(
            model_name='proceeding',
            name='issue',
            field=models.ForeignKey(default=114, on_delete=django.db.models.deletion.CASCADE, related_name='proceedings', to='journals.Issue'),
            preserve_default=False,
        ),
    ]
