# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0004_auto_20171019_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceedings',
            options={'verbose_name': 'Proceedings', 'verbose_name_plural': 'Proceedings'},
        ),
        migrations.AlterField(
            model_name='proceedings',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings', to='journals.Issue'),
        ),
    ]
