# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_fellowship_guest'),
        ('proceedings', '0005_auto_20171019_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceedings',
            name='open_for_submission',
        ),
        migrations.AddField(
            model_name='proceedings',
            name='event_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proceedings',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceedings',
            name='event_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='proceedings',
            name='event_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceedings',
            name='lead_fellow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='colleges.Fellowship'),
        ),
        migrations.AddField(
            model_name='proceedings',
            name='submissions_close',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proceedings',
            name='submissions_deadline',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proceedings',
            name='submissions_open',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
    ]
