__copyright__ = "Copyright © Stichting SciPost (SciPost Foundation)"
__license__ = "AGPL v3"


import uuid

from django.db import models
from django.db.models.functions import Cast, Coalesce
from django.urls import reverse
from scipost.behaviors import TimeStampedModel

from ..constants import PLAGIARISM_STATUSES, STATUS_WAITING

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .submission import Submission

class iThenticateReport(TimeStampedModel):
    """iThenticate plagiarism report for a Submission."""

    sub_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    to_submission = models.OneToOneField["Submission"](
        "submissions.Submission",
        related_name="iThenticate_plagiarism_report",
        on_delete=models.CASCADE,
    )

    percent_match = models.GeneratedField(
        expression=Coalesce(
            Cast(
                models.F("report_raw_data__overall_match_percentage"),
                models.IntegerField(),
            ),
            0.0,
        ),
        output_field=models.IntegerField(),
        db_persist=True,
    )
    status = models.CharField(
        max_length=16, choices=PLAGIARISM_STATUSES, default=STATUS_WAITING
    )
    old_data = models.JSONField[dict[str, Any]](
        default=dict,
        blank=True,
        help_text="Deprecated field to hold iThenticate v1 data, kept for later migration matching.",
    )
    submission_raw_data = models.JSONField[dict[str, Any]](default=dict, blank=True)
    report_raw_data = models.JSONField[dict[str, Any]](default=dict, blank=True)
    created_time = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Time when the report was created in iThenticate.",
    )
    uploaded_time = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Time when the Submission document was uploaded to iThenticate.",
    )
    requested_time = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Time when the report was requested from iThenticate.",
    )
    generated_time = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Time when the report was generated by iThenticate.",
    )

    class Meta:
        verbose_name = "iThenticate Report"
        verbose_name_plural = "iThenticate Reports"

    def __str__(self):
        """Summary of the iThenticateReport's meta information."""
        return f"iThenticate Plagiarism Report on {self.to_submission.preprint.identifier_w_vn_nr}"

    def save(self, *args, **kwargs):
        """On save, touch the Submission's latest update timestamp."""
        obj = super().save(*args, **kwargs)
        if kwargs.get("commit", True):
            self.to_submission.touch()
        return obj

    def get_absolute_url(self):
        """Return the url of the Submission's plagiarism report detail page."""
        return reverse(
            "submissions:plagiarism",
            kwargs={
                "identifier_w_vn_nr": self.to_submission.preprint.identifier_w_vn_nr
            },
        )

    def get_report_url(self):
        """Request and return new read-only url from the iThenticate API.

        Note: The read-only link is valid for only 15 minutes, saving may be worthless.
        """
        if not self.sub_id:
            return ""

        from ..plagiarism import iThenticate

        plagiarism = iThenticate()
        return plagiarism.get_url(self.sub_id)

    @property
    def processed(self):
        return self.generated_time is not None

    @property
    def score(self):
        """Return the iThenticate score returned by their API as saved in the database."""
        return self.percent_match
