# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0002_proceedings_minimum_referees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceedings',
            name='lead_fellow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='colleges.Fellowship'),
        ),
    ]
