# Generated by Django 2.2.11 on 2020-08-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0007_auto_20190910_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceedings',
            name='picture',
            field=models.ImageField(blank=True, upload_to='proceedings/images/'),
        ),
        migrations.AddField(
            model_name='proceedings',
            name='picture_credit',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
