# Generated by Django 2.2.16 on 2021-04-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proceedings", "0008_auto_20200810_1409"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proceedings",
            name="fellowships",
            field=models.ManyToManyField(
                blank=True, related_name="proceedings", to="colleges.Fellowship"
            ),
        ),
    ]
