# Generated by Django 3.2.18 on 2023-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0009_auto_20210422_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceedings',
            name='preface_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proceedings',
            name='preface_title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
