# Generated by Django 4.2.10 on 2024-03-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0047_fellowshipnominationvotinground_type"),
        ("proceedings", "0010_add_proceedings_preface"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proceedings",
            name="fellowships",
            field=models.ManyToManyField(blank=True, to="colleges.fellowship"),
        ),
    ]
