# Generated by Django 4.2.15 on 2024-09-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proceedings", "0011_alter_proceedings_fellowships"),
    ]

    operations = [
        migrations.AddField(
            model_name="proceedings",
            name="metadata_xml",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="proceedings",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
