# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualmeetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='webpage',
            field=models.URLField(),
        ),
    ]
