# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-05 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0024_auto_20190405_2102'),
        ('virtualmeetings', '0002_auto_20190126_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='VGM',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='by',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='VGM',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='in_agreement',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='in_disagreement',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='in_notsure',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='put_forward_by',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='VGM',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='by',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='in_agreement',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='in_disagreement',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='in_notsure',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Motion',
        ),
        migrations.DeleteModel(
            name='Nomination',
        ),
        migrations.DeleteModel(
            name='VGM',
        ),
    ]
