# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eicrecommendation",
            name="recommendation",
            field=models.SmallIntegerField(
                choices=[
                    (None, "-"),
                    (
                        1,
                        "Publish as Tier I (top 10% of papers in this journal, qualifies as Select)",
                    ),
                    (2, "Publish as Tier II (top 50% of papers in this journal)"),
                    (3, "Publish as Tier III (meets the criteria of this journal)"),
                    (-1, "Ask for minor revision"),
                    (-2, "Ask for major revision"),
                    (-3, "Reject"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="recommendation",
            field=models.SmallIntegerField(
                choices=[
                    (None, "-"),
                    (
                        1,
                        "Publish as Tier I (top 10% of papers in this journal, qualifies as Select)",
                    ),
                    (2, "Publish as Tier II (top 50% of papers in this journal)"),
                    (3, "Publish as Tier III (meets the criteria of this journal)"),
                    (-1, "Ask for minor revision"),
                    (-2, "Ask for major revision"),
                    (-3, "Reject"),
                ]
            ),
        ),
    ]
