# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_report_report_type'),
        ('submissions', '0003_auto_20180120_1102'),
    ]

    operations = [
    ]
