# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0007_auto_20180124_1501"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eicrecommendation",
            unique_together=set([("submission", "version")]),
        ),
    ]
