# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0009_auto_20180220_2120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("Letter", "Letter (broad-interest breakthrough results)"),
                    ("Article", "Article (in-depth reports on specialized research)"),
                    (
                        "Review",
                        "Review (candid snapshot of current research in a given area)",
                    ),
                ],
                default="",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
