# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0010_auto_20180314_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="visible_pool",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="visible_public",
            field=models.BooleanField(default=False),
        ),
    ]
