# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 08:47
from __future__ import unicode_literals

import comments.behaviors
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0011_report_file_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="file_attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/reports/%Y/%m/%d/",
                validators=[
                    comments.behaviors.validate_file_extension,
                    comments.behaviors.validate_max_file_size,
                ],
            ),
        ),
    ]
