# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0015_auto_20180414_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("unassigned_incoming", "Unassigned, undergoing pre-screening"),
                    (
                        "assignment_failed",
                        "Failed to assign Editor-in-charge; manuscript rejected",
                    ),
                    (
                        "recommendation_formulated",
                        "Editorial Recommendation formulated",
                    ),
                    ("awaiting_ed_rec", "Awaiting Editorial Recommendation"),
                    ("resubmitted", "Has been resubmitted"),
                    ("accepted", "Publication decision taken: accept"),
                    ("rejected", "Publication decision taken: reject"),
                    ("withdrawn", "Withdrawn by the Authors"),
                    ("published", "Published"),
                ],
                default="unassigned",
                max_length=30,
            ),
        ),
    ]
