# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0021_auto_20180502_2029"),
        ("submissions", "0012_auto_20180519_1047"),
    ]

    operations = []
