# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0024_auto_20180519_2324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refereeinvitation",
            name="invitation_key",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
