# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0026_submission_needs_conflicts_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialassignment",
            name="date_invited",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="editorialassignment",
            name="invitation_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="editorialassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("preassigned", "Pre-assigned"),
                    ("invited", "Invited"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                    ("deprecated", "Deprecated"),
                ],
                default="preassigned",
                max_length=16,
            ),
        ),
    ]
