# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0026_auto_20180619_0821"),
        ("preprints", "0006_remove_preprint_submission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="preprint2",
            new_name="preprint",
        ),
    ]
