# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0027_auto_20180620_1935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refereeinvitation",
            name="auto_reminders_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
