# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0029_auto_20180627_1207"),
        ("submissions", "0028_auto_20180619_0826"),
    ]

    operations = []
