# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-06 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0028_auto_20180526_1336"),
        ("submissions", "0031_auto_20180717_1046"),
    ]

    operations = []
