# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0033_auto_20180819_1343"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refereeinvitation",
            options={"ordering": ["cancelled", "date_invited"]},
        ),
    ]
