# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-02 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0035_auto_20180930_1939"),
        ("submissions", "0035_refereeinvitation_profile"),
    ]

    operations = []
