# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-09 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0035_merge_20180915_1337"),
        ("submissions", "0036_merge_20181002_1358"),
    ]

    operations = []
