# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0037_merge_20181009_2050"),
    ]

    operations = [
        migrations.AddField(
            model_name="ithenticatereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Awaiting action"),
                    ("sent", "Sent succesfully, awaiting report"),
                    ("received", "Report received"),
                    ("fail_down", "Failed (downloading failed)"),
                    ("fail_up", "Failed (uploading failed)"),
                ],
                default="waiting",
                max_length=16,
            ),
        ),
    ]
