# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 05:46
from __future__ import unicode_literals

from django.db import migrations


def upload_current_plagiarism_statuses(apps, schema_editor):
    iThenticateReport = apps.get_model('submissions', 'iThenticateReport')
    iThenticateReport.objects.all().update(status='received')


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0038_ithenticatereport_status'),
    ]

    operations = [
        migrations.RunPython(upload_current_plagiarism_statuses),
    ]
