# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0005_auto_20181028_2038"),
        ("submissions", "0038_auto_20181027_1807"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="topics",
            field=models.ManyToManyField(blank=True, to="ontology.Topic"),
        ),
    ]
