# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-30 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0044_auto_20181115_1009"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_resubmission_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="successor",
                to="submissions.Submission",
            ),
        ),
    ]
