# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0047_auto_20181204_2011"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="thread_hash",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
