# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-19 07:25
from __future__ import unicode_literals

from django.db import migrations
# from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0049_auto_20181204_2040'),
    ]

    operations = [
        # TrigramExtension(),
    ]
