# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0054_submission_update_search_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="is_resubmission_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="successor",
                to="submissions.Submission",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="proceedings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="proceedings.Proceedings",
            ),
        ),
    ]
