# Generated by Django 2.1.8 on 2019-05-18 11:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0056_auto_20190518_1157"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="editorialcommunication",
            options={
                "default_related_name": "editorial_communications",
                "ordering": ["timestamp"],
            },
        ),
        migrations.AlterField(
            model_name="submission",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
