# Generated by Django 2.1.8 on 2019-09-21 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0060_submission_approaches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="domain",
        ),
    ]
