# Generated by Django 2.1.8 on 2019-10-14 19:05

from django.db import migrations


def populate_for_journal(apps, schema_editor):
    EICRecommendation = apps.get_model("submissions", "EICRecommendation")

    for eicrec in EICRecommendation.objects.all():
        eicrec.for_journal = eicrec.submission.submitted_to
        eicrec.save()


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0067_auto_20191014_2104"),
    ]

    operations = [
        migrations.RunPython(
            populate_for_journal, reverse_code=migrations.RunPython.noop
        ),
    ]
