# Generated by Django 2.1.8 on 2019-10-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0068_populate_EICRec_for_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eicrecommendation",
            name="recommendation",
            field=models.SmallIntegerField(
                choices=[
                    (None, "-"),
                    (
                        1,
                        "Publish (surpasses expectations and criteria for this Journal; among top 10%)",
                    ),
                    (
                        2,
                        "Publish (easily meets expectations and criteria for this Journal; among top 50%)",
                    ),
                    (3, "Publish (meets expectations and criteria for this Journal)"),
                    (-1, "Ask for minor revision"),
                    (-2, "Ask for major revision"),
                    (-3, "Reject"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="recommendation",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (None, "-"),
                    (
                        1,
                        "Publish (surpasses expectations and criteria for this Journal; among top 10%)",
                    ),
                    (
                        2,
                        "Publish (easily meets expectations and criteria for this Journal; among top 50%)",
                    ),
                    (3, "Publish (meets expectations and criteria for this Journal)"),
                    (-1, "Ask for minor revision"),
                    (-2, "Ask for major revision"),
                    (-3, "Reject"),
                ],
                null=True,
            ),
        ),
    ]
