# Generated by Django 2.2.11 on 2020-07-20 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0084_preprintserver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submission_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="submission date"
            ),
        ),
    ]
