# Generated by Django 2.2.11 on 2020-07-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0086_auto_20200720_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='arxiv_link',
        ),
    ]
