# Generated by Django 2.2.11 on 2020-07-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0089_auto_20200721_0658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="code_repository_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a code repository pertaining to your manuscript",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="data_repository_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a data repository pertaining to your manuscript",
            ),
        ),
    ]
