# Generated by Django 2.2.11 on 2020-07-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0090_auto_20200721_0727"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="_is_resubmission",
        ),
    ]
