# Generated by Django 2.2.16 on 2020-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0007_Branch_Field_Specialty"),
        ("submissions", "0097_remove_submission_secondary_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="preprintserver",
            name="acad_fields",
            field=models.ManyToManyField(
                blank=True, related_name="preprint_servers", to="ontology.AcademicField"
            ),
        ),
    ]
