# Generated by Django 2.2.16 on 2020-09-29 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0100_remove_preprintserver_disciplines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="discipline",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="subject_area",
        ),
    ]
