# Generated by Django 3.2.5 on 2021-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0106_auto_20210515_1128"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
