# Generated by Django 3.2.5 on 2021-10-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0109_alter_submission_proceedings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refereeinvitation",
            name="accepted",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Response pending"),
                    (True, "Accept"),
                    (False, "Decline"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
