# Generated by Django 3.2.5 on 2021-10-18 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0110_alter_refereeinvitation_accepted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="voting_fellows",
        ),
    ]
