# Generated by Django 3.2.5 on 2022-01-17 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0112_alter_submissionevent_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refereeinvitation",
            options={"ordering": ["-date_invited"]},
        ),
    ]
