# Generated by Django 3.2.14 on 2022-11-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0113_alter_refereeinvitation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="internal_plagiarism_matches",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
