# Generated by Django 3.2.16 on 2023-01-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_alter_profile_title'),
        ('submissions', '0135_submissionauthorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionauthorprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.profile'),
        ),
    ]
