# Generated by Django 3.2.16 on 2023-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0128_populate_submission_object_types"),
        ("submissions", "0138_auto_20230120_2100"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="followup_of",
            field=models.ManyToManyField(
                blank=True, related_name="followups", to="journals.Publication"
            ),
        ),
    ]
