# Generated by Django 3.2.18 on 2024-01-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0142_alter_submission_author_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='auto_updated_fellowship',
            field=models.BooleanField(default=True),
        ),
    ]
