# Generated by Django 3.2.18 on 2024-02-02 11:02

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0143_submission_auto_updated_fellowship"),
    ]

    operations = [
        UnaccentExtension(),
    ]
