# Generated by Django 3.2.18 on 2024-02-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0146_submission_lifetime_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeinvitation',
            name='other_refusal_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='editorialassignment',
            name='refusal_reason',
            field=models.CharField(blank=True, choices=[('OFE', 'Outside of my field of expertise'), ('BUS', 'Too busy'), ('VAC', 'Away on vacation'), ('COI', 'Conflict of interest: coauthor in last 5 years'), ('CCC', 'Conflict of interest: close colleague'), ('CCM', 'Conflict of interest: close competitor'), ('COT', 'Conflict of interest: other'), ('NIR', 'Cannot give an impartial assessment'), ('NIE', 'Not interested enough'), ('DNP', 'SciPost should desk reject this paper'), ('OTH', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='refereeinvitation',
            name='refusal_reason',
            field=models.CharField(blank=True, choices=[('OFE', 'Outside of my field of expertise'), ('BUS', 'Too busy'), ('VAC', 'Away on vacation'), ('COI', 'Conflict of interest: coauthor in last 5 years'), ('CCC', 'Conflict of interest: close colleague'), ('CCM', 'Conflict of interest: close competitor'), ('COT', 'Conflict of interest: other'), ('NIR', 'Cannot give an impartial assessment'), ('NIE', 'Not interested enough'), ('DNP', 'SciPost should desk reject this paper'), ('OTH', 'Other')], max_length=3, null=True),
        ),
    ]
