# Generated by Django 4.2.10 on 2024-03-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "scipost",
            "0041_alter_remark_contributor_alter_remark_recommendation_and_more",
        ),
        ("submissions", "0147_auto_20240220_1404"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorialassignment",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="submissions.submission"
            ),
        ),
        migrations.AlterField(
            model_name="editorialassignment",
            name="to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scipost.contributor"
            ),
        ),
        migrations.AlterField(
            model_name="editorialcommunication",
            name="referee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scipost.contributor",
            ),
        ),
        migrations.AlterField(
            model_name="editorialcommunication",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="submissions.submission"
            ),
        ),
    ]
