# Generated by Django 4.2.10 on 2024-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0148_alter_editorialassignment_submission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualification",
            name="expertise_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("expert", "Expert"),
                    ("very_knowledgeable", "Very knowledgeable"),
                    ("knowledgeable", "Knowledgeable"),
                    ("marginally_qualified", "Marginally qualified"),
                    ("not_really_qualified", "Not really qualified"),
                    ("not_at_all_qualified", "Not at all qualified"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="readiness",
            name="status",
            field=models.CharField(
                choices=[
                    ("perhaps_later", "Perhaps later"),
                    (
                        "could_if_transferred",
                        "I could, if transferred to lower journal",
                    ),
                    ("too_busy", "I would, but I'm currently too busy"),
                    ("not_interested", "I won't, I'm not interested enough"),
                    ("desk_reject", "I won't, and vote for desk rejection"),
                ],
                max_length=32,
            ),
        ),
    ]
