# Generated by Django 4.2.10 on 2024-03-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0149_alter_qualification_expertise_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="code_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Information about the software referenced in the codebases publication",
            ),
        ),
    ]
