# Generated by Django 4.2.10 on 2024-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0151_submission_acceptance_elaboration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="fulfilled_expectations",
            field=models.CharField(blank=True, default=str, max_length=1000),
        ),
    ]
