# Generated by Django 4.2.10 on 2024-07-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0153_submission_fulfilled_expectations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("vetted", "Vetted"),
                    ("unvetted", "Unvetted"),
                    ("incorrect", "Rejected (incorrect)"),
                    ("unclear", "Rejected (unclear)"),
                    ("notuseful", "Rejected (not useful)"),
                    ("notacademic", "Rejected (not academic in style)"),
                    ("duplicate", "Rejected (duplicate)"),
                ],
                default="unvetted",
                max_length=16,
            ),
        ),
    ]
