# Generated by Django 4.2.10 on 2024-06-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0040_profile_first_name_original_and_more"),
        ("submissions", "0155_alter_editorialcommunication_comtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefereeIndication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indication",
                    models.CharField(
                        choices=[
                            ("suggest", "Suggest"),
                            ("advise_against", "Advise against"),
                        ],
                        max_length=256,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=64, null=True)),
                ("last_name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=256, null=True),
                ),
                (
                    "affiliation",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "indicated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_indications_made",
                        to="profiles.profile",
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_indications_received",
                        to="profiles.profile",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_indications",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "referee")},
            },
        ),
    ]
