# Generated by Django 4.2.15 on 2024-09-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "scipost",
            "0041_alter_remark_contributor_alter_remark_recommendation_and_more",
        ),
        ("submissions", "0156_refereeindication"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymizedReportContributor",
            fields=[
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="anonymized_author_table",
                        serialize=False,
                        to="submissions.report",
                    ),
                ),
                (
                    "invitation_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address to which the (accepted) invitation was sent.",
                        max_length=254,
                    ),
                ),
                (
                    "anonymized_author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="anonymized_reports_as",
                        to="scipost.contributor",
                    ),
                ),
                (
                    "original_author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymized_reports",
                        to="scipost.contributor",
                    ),
                ),
            ],
        ),
    ]
