# Generated by Django 4.2.15 on 2024-09-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0157_anonymizedreportcontributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="on_hold",
            field=models.BooleanField(default=False),
        ),
    ]
