# Generated by Django 4.2.15 on 2024-09-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0158_submission_on_hold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="reporting_deadline",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
