# Generated by Django 4.2.15 on 2024-09-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0159_alter_submission_reporting_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="refereeinvitation",
            name="intended_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
