# Generated by Django 4.2.15 on 2024-09-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0043_alter_profile_first_name_original_and_more"),
        ("submissions", "0160_refereeinvitation_intended_delivery_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refereeinvitation",
            name="title",
        ),
        migrations.RemoveField(
            model_name="refereeinvitation",
            name="referee",
        ),
        migrations.RemoveField(
            model_name="refereeinvitation",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="refereeinvitation",
            name="last_name",
        ),
        migrations.RenameField(
            model_name="refereeinvitation",
            old_name="profile",
            new_name="referee",
        ),
    ]
