# Generated by Django 4.2.15 on 2024-09-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0043_alter_profile_first_name_original_and_more"),
        ("submissions", "0161_remove_refereeinvitation_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refereeinvitation",
            name="referee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referee_invitations",
                to="profiles.profile",
            ),
        ),
    ]
