# Generated by Django 4.2.15 on 2024-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0164_conditionalassignmentoffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditionalassignmentoffer",
            name="condition_type",
            field=models.CharField(
                choices=[("JournalTransfer", "Journal Transfer")], max_length=32
            ),
        ),
    ]
