# Generated by Django 4.2.15 on 2024-11-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0166_alter_readiness_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="refereeindication",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="refereeindication",
            constraint=models.UniqueConstraint(
                fields=("submission", "indicated_by", "referee"),
                name="unique_referee_indication",
            ),
        ),
    ]
