# Generated by Django 5.0.12 on 2025-07-24 10:23

import django.db.models.deletion
from django.db import migrations, models


def convert_contributor_to_profile(apps, schema_editor):
    EditorialCommunication = apps.get_model("submissions", "EditorialCommunication")

    comms = list(
        EditorialCommunication.objects.filter(referee__isnull=False).select_related(
            "referee__profile"
        )
    )
    for comm in comms:
        comm.referee_profile = comm.referee.profile

    EditorialCommunication.objects.bulk_update(comms, ["referee_profile"])


def convert_profile_to_contributor(apps, schema_editor):
    EditorialCommunication = apps.get_model("submissions", "EditorialCommunication")

    comms = list(
        EditorialCommunication.objects.filter(
            referee_profile__isnull=False
        ).select_related("referee_profile__contributor")
    )
    for comm in comms:
        try:
            comm.referee = comm.referee_profile.contributor
        except:
            comm.referee = None

    EditorialCommunication.objects.bulk_update(comms, ["referee"])


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0047_profileemail_domain"),
        ("submissions", "0169_delete_anonymizedreportcontributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialcommunication",
            name="referee_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
        ),
        migrations.RunPython(
            code=convert_contributor_to_profile,
            reverse_code=convert_profile_to_contributor,
            atomic=True,
            elidable=True,
        ),
        migrations.RemoveField(
            model_name="editorialcommunication",
            name="referee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scipost.Contributor",
            ),
        ),
        migrations.RenameField(
            model_name="editorialcommunication",
            old_name="referee_profile",
            new_name="referee",
        ),
    ]
