# Generated by Django 5.2.5 on 2025-09-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0170_alter_editorialcommunication_referee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="needs_conflicts_update",
            new_name="needs_coauthorships_update",
        ),
    ]
