# Generated by Django 5.2.5 on 2026-02-10 13:12

import django.db.models.deletion
from django.db import connection, migrations, models

MODEL_NAMES = ["Qualification", "Readiness"]


def fellowship_to_contributor(apps, schema_editor):
    for model_name in MODEL_NAMES:
        print(f"Processing {model_name}...")
        model = apps.get_model("submissions", model_name)

        duplicate_groups = (
            model.objects.values("fellow__contributor_id", "submission_id")
            .annotate(count=models.Count("id"))
            .filter(count__gt=1)
            .values_list("fellow__contributor_id", "submission_id")
        )

        duplicate_ids = set()
        for contributor_id, submission_id in duplicate_groups:
            duplicates = (
                model.objects.all()
                .filter(
                    fellow__contributor_id=contributor_id,
                    submission_id=submission_id,
                )
                .order_by("-datetime")
            )
            duplicate_ids.update(
                duplicates.all()
                .exclude(id=duplicates.first().id)
                .values_list("id", flat=True)
            )
            model.objects.filter(id__in=duplicate_ids).delete()

        print(f"Deleted {len(duplicate_ids)} duplicate {model_name} entries.")

        objects = model.objects.exclude(id__in=duplicate_ids).select_related("fellow")
        for obj in objects:
            obj.contributor_id = obj.fellow.contributor_id

        model.objects.bulk_update(objects, ["contributor_id"])


def contributor_to_fellowship(apps, schema_editor):
    for model_name in MODEL_NAMES:
        model = apps.get_model("submissions", model_name)

        objects = model.objects.all().select_related("submission")
        for obj in objects:
            obj.fellow_id = obj.submission.fellows.get(
                contributor_id=obj.contributor_id
            ).id

        model.objects.bulk_update(objects, ["fellow_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("scipost", "0046_contributor_anonymous_stats"),
        (
            "submissions",
            "0171_rename_needs_conflicts_update_submission_needs_coauthorships_update",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qualification",
            options={
                "default_related_name": "qualifications",
                "ordering": ["submission", "fellow"],
            },
        ),
        migrations.AlterModelOptions(
            name="readiness",
            options={
                "default_related_name": "readinesses",
                "ordering": ["submission", "fellow"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="qualification",
            name="unique_together_submission_fellow",
        ),
        migrations.RemoveConstraint(
            model_name="readiness",
            name="readiness_unique_together_submission_fellow",
        ),
        migrations.AddField(
            model_name="qualification",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scipost.contributor",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="readiness",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scipost.contributor",
                null=True,
            ),
        ),
        migrations.RunPython(fellowship_to_contributor, contributor_to_fellowship),
        migrations.RemoveField(
            model_name="qualification",
            name="fellow",
        ),
        migrations.RemoveField(
            model_name="readiness",
            name="fellow",
        ),
        migrations.RenameField(
            model_name="qualification",
            old_name="contributor",
            new_name="fellow",
        ),
        migrations.RenameField(
            model_name="readiness",
            old_name="contributor",
            new_name="fellow",
        ),
        migrations.AddConstraint(
            model_name="qualification",
            constraint=models.UniqueConstraint(
                fields=("submission", "fellow"),
                name="qualification_unique_together_submission_fellow",
            ),
        ),
        migrations.AddConstraint(
            model_name="readiness",
            constraint=models.UniqueConstraint(
                fields=("submission", "fellow"),
                name="readiness_unique_together_submission_fellow",
            ),
        ),
    ]
