# Generated by Django 5.2.5 on 2026-02-12 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0046_contributor_anonymous_stats"),
        (
            "submissions",
            "0172_alter_qualification_options_alter_readiness_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualification",
            name="fellow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scipost.contributor"
            ),
        ),
        migrations.AlterField(
            model_name="readiness",
            name="fellow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scipost.contributor"
            ),
        ),
    ]
