# Generated by Django 5.2.5 on 2026-02-12 13:59

from django.db import migrations, models


def move_metadata_fields_to_article(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")

    submissions = list(Submission.objects.all())
    for submission in submissions:
        article_metadata = {
            "code_repository_url": submission.code_repository_url,
            "data_repository_url": submission.data_repository_url,
            **submission.code_metadata,
        }
        submission.article_metadata = article_metadata

    Submission.objects.bulk_update(submissions, ["article_metadata"])


def move_article_metadata_to_fields(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")

    submissions = list(Submission.objects.all())
    for submission in submissions:
        submission.code_metadata = {
            key: value
            for key, value in submission.article_metadata.items()
            if key.startswith("code_") and not key.endswith("_repository_url")
        }
        submission.code_repository_url = submission.article_metadata.get(
            "code_repository_url", ""
        )
        submission.data_repository_url = submission.article_metadata.get(
            "data_repository_url", ""
        )

    Submission.objects.bulk_update(
        submissions,
        [
            "code_repository_url",
            "data_repository_url",
            "code_metadata",
        ],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0173_alter_qualification_fellow_alter_readiness_fellow"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="article_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Specific information about the article, depending on the target journal's needs. Not actual metadata to be deposited.",
            ),
        ),
        migrations.RunPython(
            move_metadata_fields_to_article, move_article_metadata_to_fields
        ),
        migrations.RemoveField(
            model_name="submission",
            name="code_metadata",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="code_repository_url",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="data_repository_url",
        ),
    ]
