# Generated by Django 5.2.5 on 2026-04-09 13:39

from typing import Any

from django.db import migrations, models


def update_keys_migration(app: str, model: str, field: str, key_map: dict[Any, Any]):
    def update(apps, schema_editor):
        Model = apps.get_model(app, model)
        for old_key, new_key in key_map.items():
            Model.objects.filter(**{field: old_key}).update(**{field: new_key})

    def reverse_update(apps, schema_editor):
        Model = apps.get_model(app, model)
        for new_key, old_key in key_map.items():
            Model.objects.filter(**{field: new_key}).update(**{field: old_key})

    return update, reverse_update


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0174_remove_submission_code_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternativerecommendation",
            name="recommendation",
            field=models.CharField(
                choices=[
                    ("publish", "Publish"),
                    ("reconsult_referees", "Reconsult previous referees"),
                    ("seek_additional_referees", "Seek additional referees"),
                    ("minor_revision", "Ask for minor revision"),
                    ("major_revision", "Ask for major revision"),
                    ("reject", "Reject"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(
            *update_keys_migration(
                "submissions",
                "alternativerecommendation",
                "recommendation",
                {
                    1: "publish",
                    -1: "minor_revision",
                    -2: "major_revision",
                    -3: "reject",
                    -4: "reconsult_referees",
                    -5: "seek_additional_referees",
                },
            ),
        ),
        migrations.AlterField(
            model_name="editorialdecision",
            name="decision",
            field=models.CharField(
                choices=[("publish", "Publish"), ("reject", "Reject")],
                max_length=32,
            ),
        ),
        migrations.RunPython(
            *update_keys_migration(
                "submissions",
                "editorialdecision",
                "decision",
                {1: "publish", -3: "reject"},
            ),
        ),
        migrations.AlterField(
            model_name="eicrecommendation",
            name="recommendation",
            field=models.CharField(
                choices=[
                    ("publish", "Publish"),
                    ("minor_revision", "Ask for minor revision"),
                    ("major_revision", "Ask for major revision"),
                    ("reject", "Reject"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(
            *update_keys_migration(
                "submissions",
                "eicrecommendation",
                "recommendation",
                {
                    1: "publish",
                    -1: "minor_revision",
                    -2: "major_revision",
                    -3: "reject",
                },
            ),
        ),
    ]
