# Generated by Django 5.2.5 on 2026-06-25 12:46

from django.db import migrations, models


def status_to_bool(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")
    Submission.objects.update(
        needs_coauthorships_update=models.Case(
            models.When(
                coauthorships_update_status=models.Value("fetched"),
                then=False,
            ),
            default=True,
            output_field=models.BooleanField(),
        )
    )


def bool_to_status(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")
    Submission.objects.all().update(
        coauthorships_update_status=models.Case(
            models.When(
                needs_coauthorships_update=True,
                then=models.Value("unknown"),
            ),
            default=models.Value("fetched"),
            output_field=models.CharField(max_length=30),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0175_alter_submission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="coauthorships_update_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("fetching", "Fetching"),
                    ("fetched", "Fetched"),
                    ("failed", "Failed"),
                ],
                default="unknown",
                max_length=30,
            ),
        ),
        migrations.RunPython(bool_to_status, reverse_code=status_to_bool),
        migrations.RemoveField(
            model_name="submission",
            name="needs_coauthorships_update",
        ),
    ]
