# Generated by Django 5.2.5 on 2026-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0175_alter_alternativerecommendation_recommendation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternativerecommendation",
            name="recommendation",
            field=models.CharField(
                choices=[
                    ("publish", "Publish"),
                    ("minor_revision", "Ask for minor revision"),
                    ("major_revision", "Ask for major revision"),
                    ("reject", "Reject"),
                    ("accept_corrections", "Accept corrections"),
                    ("no_update_needed", "No update needed"),
                    ("dismiss_concerns", "Dismiss concerns"),
                    ("retract_publication", "Retract publication"),
                    ("reconsult_referees", "Reconsult previous referees"),
                    ("seek_additional_referees", "Seek additional referees"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="eicrecommendation",
            name="recommendation",
            field=models.CharField(
                choices=[
                    ("publish", "Publish"),
                    ("minor_revision", "Ask for minor revision"),
                    ("major_revision", "Ask for major revision"),
                    ("reject", "Reject"),
                    ("accept_corrections", "Accept corrections"),
                    ("no_update_needed", "No update needed"),
                    ("dismiss_concerns", "Dismiss concerns"),
                    ("retract_publication", "Retract publication"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="editorialdecision",
            name="decision",
            field=models.CharField(
                choices=[
                    ("publish", "Publish"),
                    ("reject", "Reject"),
                    ("accept_corrections", "Accept corrections"),
                    ("no_update_needed", "No update needed"),
                    ("dismiss_concerns", "Dismiss concerns"),
                    ("retract_publication", "Retract publication"),
                ],
                max_length=32,
            ),
        ),
    ]
