# Generated by Django 5.2.5 on 2026-09-25 11:43

from datetime import datetime

import django.db.models.functions.comparison
import uuid
from django.db import migrations, models


def handle_old_fields(apps, schema_editor):
    iThenticateReport = apps.get_model("submissions", "iThenticateReport")

    reports = list(iThenticateReport.objects.all())
    for report in reports:
        report.old_data = {
            "doc_id": report.doc_id,
            "part_id": report.part_id,
            "percent_match": report.percent_match,
            "processed_time": processed_time.isoformat()
            if (processed_time := report.processed_time)
            else None,
        }
        report.report_raw_data |= {"overall_match_percentage": report.percent_match}

    iThenticateReport.objects.bulk_update(
        reports, ["old_data", "report_raw_data"], batch_size=1000
    )


def restore_old_fields(apps, schema_editor):
    iThenticateReport = apps.get_model("submissions", "iThenticateReport")

    reports = list(iThenticateReport.objects.all())
    for report in reports:
        report.doc_id = report.old_data.get("doc_id")
        report.part_id = report.old_data.get("part_id")
        report.processed_time = (
            datetime.fromisoformat(processed_time)
            if (processed_time := report.old_data.get("processed_time"))
            else None
        )
        report.percent_match = report.old_data.get("percent_match", 0)

    iThenticateReport.objects.bulk_update(
        reports,
        ["doc_id", "part_id", "processed_time", "percent_match"],
        batch_size=1000,
    )


def convert_doc_id_to_uuid(apps, schema_editor):
    iThenticateReport = apps.get_model("submissions", "iThenticateReport")

    reports = list(iThenticateReport.objects.all())
    for report in reports:
        if doc_id := report.old_data.get("doc_id"):
            report.sub_id = uuid.UUID(int=doc_id)

    iThenticateReport.objects.bulk_update(reports, ["sub_id"], batch_size=1000)


def save_submission_id_to_report(apps, schema_editor):
    iThenticateReport = apps.get_model("submissions", "iThenticateReport")

    reports = list(iThenticateReport.objects.all())
    for report in reports:
        if submission := getattr(report, "to_submission", None):
            report.old_data |= {"submission_id": submission.id}

    iThenticateReport.objects.bulk_update(reports, ["old_data"], batch_size=1000)


def restore_submission_id_from_report(apps, schema_editor):
    iThenticateReport = apps.get_model("submissions", "iThenticateReport")
    Submission = apps.get_model("submissions", "Submission")

    reports = list(iThenticateReport.objects.all())
    submissions_map = dict(
        {submission.id: submission for submission in Submission.objects.all()}
    )
    for report in reports:
        if submission_id := report.old_data.get("submission_id"):
            if submission := submissions_map.get(submission_id):
                submission.iThenticate_plagiarism_report = report

    Submission.objects.bulk_update(
        submissions_map.values(), ["iThenticate_plagiarism_report"], batch_size=1000
    )


def use_submission_id_from_report(apps, schema_editor):
    iThenticateReport = apps.get_model("submissions", "iThenticateReport")

    reports = list(iThenticateReport.objects.all())
    reports_to_update = []
    report_ids_to_delete = []
    for report in reports:
        if submission_id := report.old_data.get("submission_id"):
            report.to_submission_id = submission_id
            reports_to_update.append(report)
        else:
            report_ids_to_delete.append(report.pk)

    iThenticateReport.objects.bulk_update(
        reports_to_update, ["to_submission_id"], batch_size=1000
    )
    iThenticateReport.objects.filter(pk__in=report_ids_to_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0178_alter_eicrecommendation_recommendation"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="ithenticatereport",
            name="old_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Deprecated field to hold iThenticate v1 data, kept for later migration matching.",
            ),
        ),
        migrations.AddField(
            model_name="ithenticatereport",
            name="report_raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ithenticatereport",
            name="submission_raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(
            code=handle_old_fields,
            reverse_code=restore_old_fields,
        ),
        migrations.RunPython(
            code=save_submission_id_to_report,
            reverse_code=restore_submission_id_from_report,
        ),
        migrations.RemoveField(
            model_name="submission",
            name="iThenticate_plagiarism_report",
        ),
        migrations.RemoveField(
            model_name="ithenticatereport",
            name="percent_match",
        ),
        migrations.AddField(
            model_name="ithenticatereport",
            name="percent_match",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    django.db.models.functions.comparison.Cast(
                        models.F("report_raw_data__overall_match_percentage"),
                        models.IntegerField(),
                    ),
                    0,
                ),
                output_field=models.IntegerField(),
            ),
        ),
        migrations.AddField(
            model_name="ithenticatereport",
            name="sub_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=False, serialize=False
            ),
        ),
        migrations.RunPython(
            code=convert_doc_id_to_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="ithenticatereport",
            name="doc_id",
        ),
        migrations.RemoveField(
            model_name="ithenticatereport",
            name="part_id",
        ),
        migrations.RemoveField(
            model_name="ithenticatereport",
            name="processed_time",
        ),
        migrations.AlterField(
            model_name="ithenticatereport",
            name="sub_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="ithenticatereport",
            name="to_submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="iThenticate_plagiarism_report",
                to="submissions.submission",
                null=True,
            ),
        ),
        migrations.RunPython(
            use_submission_id_from_report, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="ithenticatereport",
            name="to_submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="iThenticate_plagiarism_report",
                to="submissions.submission",
                null=False,
            ),
        ),
        migrations.AddField(
            model_name="ithenticatereport",
            name="created_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the report was created in iThenticate.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ithenticatereport",
            name="generated_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the report was generated by iThenticate.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ithenticatereport",
            name="requested_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the report was requested from iThenticate.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ithenticatereport",
            name="uploaded_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the Submission document was uploaded to iThenticate.",
                null=True,
            ),
        ),
    ]
