# Generated by Django 5.2.5 on 2026-08-05 15:44

import django.db.models.deletion
import scipost.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0046_contributor_anonymous_stats"),
        ("submissions", "0178_alter_eicrecommendation_recommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drafted", "Drafted"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("deprecated", "Deprecated"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "appeal_letter_text",
                    models.TextField(
                        help_text="Text of the appeal letter submitted by the authors",
                        verbose_name="Appeal letter text",
                    ),
                ),
                (
                    "appeal_letter_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=scipost.storage.SecureFileStorage(),
                        upload_to="uploads/appeals/%Y/%m/%d/",
                        verbose_name="Appeal letter attachment",
                    ),
                ),
                (
                    "remarks_edadmin",
                    models.TextField(
                        blank=True,
                        help_text="Remarks by editorial administration to adjudicating fellows",
                        null=True,
                        verbose_name="Remarks from Editorial Administration",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "adjudicators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="appeals_adjudicated",
                        to="scipost.contributor",
                    ),
                ),
                (
                    "editorial_decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeal",
                        to="submissions.editorialdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-editorial_decision__submission"],
                "default_related_name": "appeals",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("editorial_decision",), name="unique_editorial_decision"
                    )
                ],
            },
        ),
    ]
