# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scipost', '0039_auto_20170306_0804'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('headline', models.CharField(max_length=300)),
                ('blurb', models.TextField()),
                ('followup_link', models.URLField(blank=True, null=True)),
                ('followup_link_text', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'scipost_newsitem',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
