# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
