# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170812_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='followup_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='followup_link_text',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
    ]
