# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funder',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['funder', 'recipient', 'recipient_name', 'number']},
        ),
    ]
