# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0002_auto_20170725_2011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grant',
            unique_together=set([('funder', 'number')]),
        ),
    ]
