# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0003_auto_20170726_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funder',
            options={'ordering': ['name', 'acronym']},
        ),
        migrations.AddField(
            model_name='funder',
            name='acronym',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
