# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-27 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0004_auto_20170726_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='further_details',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
