# Generated by Django 2.1.8 on 2019-05-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0012_auto_20180922_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'default_related_name': 'grants', 'ordering': ['funder', 'recipient', 'recipient_name', 'number']},
        ),
    ]
