# Generated by Django 3.2.18 on 2023-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_alter_profile_title'),
        ('colleges', '0039_nomination_add_events'),
        ('series', '0006_collection_expected_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='expected_editors',
            field=models.ManyToManyField(blank=True, related_name='collections_editing', to='colleges.Fellowship'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='expected_authors',
            field=models.ManyToManyField(blank=True, related_name='collections_authoring', to='profiles.Profile'),
        ),
    ]
