# Generated by Django 3.2.18 on 2023-09-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0128_populate_submission_object_types'),
        ('submissions', '0142_alter_submission_author_list'),
        ('series', '0007_collection_expected_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='publications',
            field=models.ManyToManyField(blank=True, related_name='collections', through='series.CollectionPublicationsTable', to='journals.Publication'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='series.series'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='collections', to='submissions.Submission'),
        ),
        migrations.AlterField(
            model_name='series',
            name='container_journals',
            field=models.ManyToManyField(blank=True, related_name='contained_series', to='journals.Journal'),
        ),
    ]
