# Generated by Django 3.2.18 on 2023-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_alter_collections_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='event_details',
            field=models.TextField(blank=True, help_text='The details of the event, to be displayed as information about the collection in the paper.'),
        ),
    ]
