# Generated by Django 5.0.12 on 2025-05-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("series", "0010_collection_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="enforce_expected_authors",
            field=models.BooleanField(
                default=True,
                help_text="If checked, only authors in the expected_authors list can submit to this collection.",
            ),
        ),
    ]
