# Generated by Django 5.0.12 on 2025-07-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("series", "0011_collection_enforce_expected_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="editor_considerations",
            field=models.TextField(
                blank=True,
                help_text="Special rules enforced in this Collection, affecting the editors.",
            ),
        ),
    ]
