# Generated by Django 5.0.12 on 2025-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("series", "0012_collection_editor_considerations"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="enforce_assignment_deadline",
            field=models.BooleanField(default=False),
        ),
    ]
