# Generated by Django 5.2.5 on 2025-09-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0140_alter_issue_doi_label_alter_journal_doi_label_and_more"),
        ("series", "0013_collection_enforce_assignment_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="allowed_in_journals",
            field=models.ManyToManyField(
                blank=True,
                help_text="Limits the related submissions' alternative journals to this set.",
                related_name="collections_allowed",
                to="journals.journal",
            ),
        ),
    ]
