# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("conflicts", "0002_auto_20180525_1433"),
    ]

    operations = [
        migrations.AddField(
            model_name="conflictofinterest",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conflictofinterest",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
