# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conflicts", "0005_auto_20180526_0906"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conflictgroup",
            name="conflicts",
        ),
        migrations.AddField(
            model_name="conflictofinterest",
            name="conflict_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflicts",
                to="conflicts.ConflictGroup",
            ),
        ),
    ]
