# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-19 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conflicts', '0007_auto_20180526_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflictgroup',
            name='related_submissions',
        ),
        migrations.RemoveField(
            model_name='conflictofinterest',
            name='conflict_group',
        ),
        migrations.RemoveField(
            model_name='conflictofinterest',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='conflictofinterest',
            name='to_contributor',
        ),
        migrations.DeleteModel(
            name='ConflictGroup',
        ),
        migrations.DeleteModel(
            name='ConflictOfInterest',
        ),
    ]
