# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-09 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conflicts", "0013_conflictofinterest_related_submissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conflictofinterest",
            name="related_submissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="conflict_of_interests",
                to="submissions.Submission",
            ),
        ),
    ]
