# Generated by Django 5.0.12 on 2025-07-17 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conflicts", "0014_auto_20190209_1127"),
        ("profiles", "0045_profile_is_anonymous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conflictofinterest",
            name="related_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_conflicts",
                to="profiles.profile",
            ),
        ),
    ]
