# Generated by Django 5.2.5 on 2025-08-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conflicts", "0015_alter_conflictofinterest_related_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="conflictofinterest",
            name="resource_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
