# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scipost.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scipost', '0050_auto_20170416_2152'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMailchimpSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_activity', scipost.db.fields.AutoDateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailchimpList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_activity', scipost.db.fields.AutoDateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('internal_name', models.CharField(blank=True, max_length=255)),
                ('supporting_text', models.TextField(blank=True)),
                ('mailchimp_list_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=255)),
                ('allowed_groups', models.ManyToManyField(related_name='allowed_mailchimp_lists', to='auth.Group')),
            ],
            options={
                'default_permissions': ('delete',),
            },
        ),
        migrations.AddField(
            model_name='activemailchimpsubscription',
            name='active_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_lists.MailchimpList'),
        ),
        migrations.AddField(
            model_name='activemailchimpsubscription',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor'),
        ),
    ]
