# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0002_auto_20170423_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemailchimpsubscription',
            name='status',
            field=models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed')], default='subscribed', max_length=255),
        ),
    ]
