# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0003_activemailchimpsubscription_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveMailchimpSubscription',
            new_name='MailchimpSubscription',
        ),
    ]
