# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0004_auto_20170423_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailchimplist',
            name='subscriber_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
