# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commentaries", "0001_initial"),
        ("journals", "0001_initial"),
        ("scipost", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="commentaries", to="scipost.Contributor"
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="authors_claims",
            field=models.ManyToManyField(
                blank=True,
                related_name="claimed_commentaries",
                to="scipost.Contributor",
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="authors_false_claims",
            field=models.ManyToManyField(
                blank=True,
                related_name="false_claimed_commentaries",
                to="scipost.Contributor",
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_commentaries",
                to="scipost.Contributor",
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="scipost_publication",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentary",
                to="journals.Publication",
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="vetted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scipost.Contributor",
            ),
        ),
    ]
