# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commentaries", "0003_auto_20190126_2058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="scipost_publication",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commentary",
                to="journals.Publication",
            ),
        ),
    ]
