# Generated by Django 2.1.8 on 2019-05-18 11:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commentaries", "0004_auto_20190511_1141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
