# Generated by Django 2.2.16 on 2020-09-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0017_auto_20200926_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='acad_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentaries', to='ontology.AcademicField'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='specialties',
            field=models.ManyToManyField(related_name='commentaries', to='ontology.Specialty'),
        ),
    ]
