# Generated by Django 3.2.5 on 2021-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0019_auto_20200927_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
