# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-08 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forums", "0003_auto_20190307_0908"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(
                help_text='You can use ReStructuredText, see a <a href="https://devguide.python.org/documenting/#restructuredtext-primer" target="_blank">primer on python.org</a>'
            ),
        ),
    ]
