# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0004_auto_20190308_1055"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="description",
            field=models.TextField(
                blank=True,
                help_text='You can use ReStructuredText, see a <a href="https://devguide.python.org/documenting/#restructuredtext-primer" target="_blank">primer on python.org</a>',
                null=True,
            ),
        ),
    ]
