# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("forums", "0005_forum_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "forum",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="forums.Forum",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_until", models.DateField()),
                (
                    "preamble",
                    models.TextField(
                        help_text='Explanatory notes for the meeting.\nYou can use ReStructuredText, see a <a href="https://devguide.python.org/documenting/#restructuredtext-primer" target="_blank">primer on python.org</a>'
                    ),
                ),
                (
                    "minutes",
                    models.TextField(
                        blank=True,
                        help_text='To be filled in after completion of the meeting.\nYou can use ReStructuredText, see a <a href="https://devguide.python.org/documenting/#restructuredtext-primer" target="_blank">primer on python.org</a>',
                        null=True,
                    ),
                ),
            ],
            bases=("forums.forum",),
        ),
    ]
