# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-10 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forums", "0008_auto_20190310_0713"),
    ]

    operations = [
        migrations.RenameField(
            model_name="motion",
            old_name="post_ptr",
            new_name="post",
        ),
    ]
