# Generated by Django 3.2.16 on 2023-01-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_alter_meeting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='absolute_url',
            field=models.URLField(blank=True),
        ),
    ]
