# Generated by Django 3.2.16 on 2023-02-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0016_forum_cf_nr_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['name'], 'permissions': [('can_administer_forum', 'Can administer Forum'), ('can_view_forum', 'Can view Forum'), ('can_post_to_forum', 'Can add Post to Forum')]},
        ),
    ]
