# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing_lists', '0001_initial'),
        ('scipost', '0002_auto_20171229_1435'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailchimpsubscription',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_subscription', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='mailchimplist',
            name='allowed_groups',
            field=models.ManyToManyField(related_name='allowed_mailchimp_lists', to='auth.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='mailchimpsubscription',
            unique_together=set([('active_list', 'contributor')]),
        ),
    ]
