# Generated by Django 4.2.10 on 2024-04-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "scipost",
            "0041_alter_remark_contributor_alter_remark_recommendation_and_more",
        ),
        ("mailing_lists", "0002_auto_20171229_1435"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("is_opt_in", models.BooleanField(default=False)),
                (
                    "eligible_subscribers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="eligible_mailing_lists",
                        to="scipost.contributor",
                    ),
                ),
                (
                    "subscribed",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subscribed_mailing_lists",
                        to="scipost.contributor",
                    ),
                ),
            ],
        ),
    ]
