# Generated by Django 3.2.17 on 2023-04-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogpost_blurb_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="blurb_image_caption",
            field=models.TextField(blank=True),
        ),
    ]
