# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20170519_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectivePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('PR', 'Prof.'), ('DR', 'Dr'), ('MR', 'Mr'), ('MRS', 'Mrs')], max_length=4)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=128)),
                ('partner_type', models.CharField(choices=[('Int. Fund. Agency', 'International Funding Agency'), ('Nat. Fund. Agency', 'National Funding Agency'), ('Nat. Library', 'National Library'), ('Univ. Library', 'University Library'), ('Res. Library', 'Research Library'), ('Foundation', 'Foundation'), ('Individual', 'Individual')], max_length=32)),
                ('institution_name', models.CharField(max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_processed', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='MembershipQuery',
        ),
    ]
