# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20171229_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='css_class',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
