# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20170519_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectivepartner',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
