# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_institution_css_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='css_class',
            field=models.CharField(blank=True, max_length=256, verbose_name='Additional logo CSS class'),
        ),
    ]
