# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-04 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20170603_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospectivecontact',
            old_name='institution',
            new_name='prospartner',
        ),
        migrations.RemoveField(
            model_name='prospectivepartner',
            name='processed',
        ),
        migrations.AddField(
            model_name='prospectivepartner',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested (from online form)'), ('added', 'Added internally'), ('processed', 'Processed into Partner object')], default='added', max_length=32),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Contacted', 'Contacted'), ('Negotiating', 'Negotiating'), ('Uninterested', 'Uninterested'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=16),
        ),
    ]
