# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-04 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20170604_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospectivepartnerevent',
            old_name='prospective_partner',
            new_name='prospartner',
        ),
        migrations.RemoveField(
            model_name='prospectivepartnerevent',
            name='duration',
        ),
    ]
