# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20180708_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Organization'),
        ),
    ]
