# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partner_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['country', 'name']},
        ),
        migrations.AlterField(
            model_name='partner',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Organization'),
        ),
    ]
