# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20180711_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cf_nr_associated_publications',
            field=models.PositiveIntegerField(blank=True, help_text='NB: nr_associated_publications is a calculated field. Do not modify.', null=True),
        ),
    ]
