# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20170604_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectivepartnerevent',
            name='event',
            field=models.CharField(choices=[('comment', 'Comment added'), ('email_sent', 'Email sent'), ('promoted', 'Promoted to Partner')], max_length=64),
        ),
    ]
