# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import scipost.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20170608_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectivepartner',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested (from online form)'), ('added', 'Added internally'), ('approached', 'Approached'), ('processed', 'Processed into Partner')], default='added', max_length=32),
        ),
        migrations.AlterField(
            model_name='prospectivepartnerevent',
            name='event',
            field=models.CharField(choices=[('requested', 'Requested (from online form)'), (('comment',), 'Comment added'), ('email_sent', 'Email sent'), ('promoted', 'Promoted to Partner')], max_length=64),
        ),
        migrations.AlterField(
            model_name='prospectivepartnerevent',
            name='noted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(scipost.models.get_sentinel_user), to='scipost.Contributor'),
        ),
    ]
