# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_auto_20180714_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='orgtype',
            field=models.CharField(choices=[('ResearchRnstitute', 'Research Institute'), ('InternationalFundingAgency', 'International Funding Agency'), ('NationalFundingAgency', 'National Funding Agency'), ('FundingAgencyInitiative', 'Funding Agency Initiative'), ('NationalLaboratory', 'National Laboratory'), ('NationalLibrary', 'National Library'), ('NationalAcademy', 'National Academy'), ('UniversityLibrary', 'University (and its Library)'), ('ResearchLibrary', 'Research Library'), ('ProfessionalSociety', 'Professional Society'), ('InternationalConsortium', 'International Consortium'), ('NationalConsortium', 'National Consortium'), ('Foundation', 'Foundation'), ('GovernmentInternational', 'Government (international)'), ('GovernmentNational', 'Government (national)'), ('GovernmentProvincial', 'Government (provincial)'), ('GovernmentRegional', 'Government (regional)'), ('GovernmentMunicipal', 'Government (municipal)'), ('GovernmentalMinistry', 'Governmental Ministry'), ('GovernmentalOffice', 'Governmental Office'), ('BusinessCorporation', 'Business Corporation'), ('IndividualBenefactor', 'Individual Benefactor'), ('PrivateBenefactor', 'Private Benefactor')], max_length=32),
        ),
    ]
