# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20180715_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='partners.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='superseded_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.Organization'),
        ),
    ]
