# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20170609_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectivepartnerevent',
            name='event',
            field=models.CharField(choices=[('requested', 'Requested (from online form)'), ('comment', 'Comment added'), ('email_sent', 'Email sent'), ('negotiating', 'Initiated negotiation'), ('marked_as_uninterested', 'Marked as uninterested'), ('promoted', 'Promoted to Partner')], max_length=64),
        ),
    ]
