# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20170609_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='kind',
            field=models.CharField(choices=[('Res. Inst.', 'Research Institute'), ('Int. Fund. Agency', 'International Funding Agency'), ('Nat. Fund. Agency', 'National Funding Agency'), ('Nat. Lab.', 'National Laboratory'), ('Nat. Library', 'National Library'), ('Nat. Acad.', 'National Academy'), ('Univ. Library', 'University (and its Library)'), ('Res. Library', 'Research Library'), ('Prof. Soc.', 'Professional Society'), ('Nat. Consor.', 'National Consortium'), ('Foundation', 'Foundation'), ('Individual', 'Individual')], max_length=32),
        ),
        migrations.AlterField(
            model_name='prospectivepartner',
            name='kind',
            field=models.CharField(choices=[('Res. Inst.', 'Research Institute'), ('Int. Fund. Agency', 'International Funding Agency'), ('Nat. Fund. Agency', 'National Funding Agency'), ('Nat. Lab.', 'National Laboratory'), ('Nat. Library', 'National Library'), ('Nat. Acad.', 'National Academy'), ('Univ. Library', 'University (and its Library)'), ('Res. Library', 'Research Library'), ('Prof. Soc.', 'Professional Society'), ('Nat. Consor.', 'National Consortium'), ('Foundation', 'Foundation'), ('Individual', 'Individual')], default='Univ. Library', max_length=32),
        ),
        migrations.AlterField(
            model_name='prospectivepartnerevent',
            name='event',
            field=models.CharField(choices=[('requested', 'Requested (from online form)'), ('comment', 'Comment added'), ('email_sent', 'Email sent'), ('negotiating', 'Initiated negotiation'), ('marked_as_uninterested', 'Marked as uninterested'), ('promoted', 'Promoted to Partner')], max_length=64),
        ),
    ]
