# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import scipost.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20170609_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='financial_contact',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='technical_contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='consortia',
            field=models.ManyToManyField(help_text='All Consortia for which the Contact has explicit permission to view/edit its data.', to='partners.Consortium'),
        ),
        migrations.AddField(
            model_name='contact',
            name='partners',
            field=models.ManyToManyField(help_text='All Partners (+related Institutions) the Contact is related to.', to='partners.Partner'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=scipost.fields.ChoiceArrayField(base_field=models.CharField(choices=[('tech', 'Technical Contact'), ('fin', 'Financial Contact')], max_length=4), size=None),
        ),
        migrations.AlterField(
            model_name='prospectivepartnerevent',
            name='event',
            field=models.CharField(choices=[('requested', 'Requested (from online form)'), ('comment', 'Comment added'), ('email_sent', 'Email sent'), ('negotiating', 'Initiated negotiation'), ('marked_as_uninterested', 'Marked as uninterested'), ('promoted', 'Promoted to Partner')], max_length=64),
        ),
    ]
