# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-20 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_auto_20170620_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='consortia',
            field=models.ManyToManyField(blank=True, help_text='All Consortia for which the Contact has explicit permission to view/edit its data.', to='partners.Consortium'),
        ),
    ]
