# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_auto_20180715_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.Organization'),
        ),
    ]
