# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_auto_20170620_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
