# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_auto_20170620_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='contact',
            name='key_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='membershipagreement',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='partners.Partner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Contacted', 'Contacted'), ('Negotiating', 'Negotiating'), ('Uninterested', 'Uninterested'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Initiated', max_length=16),
        ),
        migrations.AlterField(
            model_name='prospectivecontact',
            name='prospartner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospective_contacts', to='partners.ProspectivePartner'),
        ),
    ]
