# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_remove_partner_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='superseded_by',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
