# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_auto_20170624_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerevent',
            name='noted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerevent',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='partners.Partner'),
        ),
    ]
