# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-07 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_auto_20180922_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='consortia',
        ),
        migrations.RemoveField(
            model_name='membershipagreement',
            name='consortium',
        ),
    ]
