# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_merge_20170624_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipagreement',
            name='offered_yearly_contribution',
            field=models.SmallIntegerField(default=0, help_text="Yearly contribution in euro's (€)"),
        ),
    ]
