# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-07 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_auto_20181007_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consortium',
            name='partners',
        ),
        migrations.DeleteModel(
            name='Consortium',
        ),
    ]
