# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import scipost.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0020_auto_20170624_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, upload_to='UPLOADS/INSTITUTIONS/LOGOS/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=scipost.fields.ChoiceArrayField(base_field=models.CharField(choices=[('gen', 'General Contact'), ('tech', 'Technical Contact'), ('fin', 'Financial Contact'), ('leg', 'Legal Contact')], max_length=4), size=None),
        ),
    ]
