# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_auto_20170626_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, upload_to='institutions/logo/%Y/'),
        ),
    ]
