# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-07 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_auto_20181007_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
