# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationevent'),
        ('partners', '0022_delete_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectivepartner',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
    ]
