# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0022_auto_20170626_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
