# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-01 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_prospectivepartner_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='membershipagreement',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='main_contact',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='partnerevent',
            name='noted_by',
        ),
        migrations.RemoveField(
            model_name='partnerevent',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partnersattachment',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='prospectivecontact',
            name='prospartner',
        ),
        migrations.RemoveField(
            model_name='prospectivepartner',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='prospectivepartnerevent',
            name='noted_by',
        ),
        migrations.RemoveField(
            model_name='prospectivepartnerevent',
            name='prospartner',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactRequest',
        ),
        migrations.DeleteModel(
            name='MembershipAgreement',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='PartnerEvent',
        ),
        migrations.DeleteModel(
            name='PartnersAttachment',
        ),
        migrations.DeleteModel(
            name='ProspectiveContact',
        ),
        migrations.DeleteModel(
            name='ProspectivePartner',
        ),
        migrations.DeleteModel(
            name='ProspectivePartnerEvent',
        ),
    ]
