# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import scipost.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_contact_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('kind', scipost.fields.ChoiceArrayField(base_field=models.CharField(choices=[('gen', 'General Contact'), ('tech', 'Technical Contact'), ('fin', 'Financial Contact'), ('leg', 'Legal Contact')], max_length=4), size=None)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('title', models.CharField(choices=[('PR', 'Prof.'), ('DR', 'Dr'), ('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms')], max_length=4)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('init', 'Request submitted by Contact'), ('proc', 'Processed'), ('decl', 'Declined')], default='init', max_length=4)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
            ],
        ),
    ]
