# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0024_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='UPLOADS/PARTNERS/ATTACHMENTS')),
                ('name', models.CharField(max_length=128)),
                ('agreement', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='partners.MembershipAgreement')),
            ],
        ),
    ]
