# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0025_partnersattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersattachment',
            name='agreement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='partners.MembershipAgreement'),
        ),
    ]
