# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0026_auto_20170627_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipagreement',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
