# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-08 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0026_auto_20170627_1809'),
        ('partners', '0012_auto_20170618_2024'),
    ]

    operations = [
    ]
