# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0027_membershipagreement_end_date'),
        ('partners', '0027_merge_20170707_1857'),
    ]

    operations = [
    ]
