# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-30 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0028_merge_20170721_1419'),
        ('partners', '0029_merge_20170726_0945'),
    ]

    operations = [
    ]
