# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0031_auto_20170815_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='_activation_key',
            new_name='activation_key',
        ),
    ]
