# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0032_auto_20170829_0727'),
    ]

    operations = [
    ]
