# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import scipost.storage


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0032_auto_20170829_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersattachment',
            name='attachment',
            field=models.FileField(storage=scipost.storage.SecureFileStorage(), upload_to='UPLOADS/PARTNERS/ATTACHMENTS'),
        ),
    ]
