# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0033_auto_20171003_1512'),
        ('partners', '0033_auto_20170930_2230'),
    ]

    operations = [
    ]
