# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0034_merge_20171004_1946'),
        ('partners', '0036_auto_20171004_2014'),
    ]

    operations = [
    ]
