# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0037_merge_20171009_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectivepartner',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested (from online form)'), ('added', 'Added internally'), ('approached', 'Approached'), ('followuped', 'Followed-up'), ('negotiating', 'Negotiating'), ('uninterested', 'Uninterested'), ('processed', 'Processed into Partner')], default='added', max_length=32),
        ),
    ]
