# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-30 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_auto_20180930_0726"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="alternativeemail",
            unique_together=set([("profile", "email")]),
        ),
    ]
