# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-02 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_auto_20181002_1104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileemail",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="profiles.Profile",
            ),
        ),
    ]
