# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-02 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20181002_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileemail',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
