# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-02 09:14
from __future__ import unicode_literals

from django.db import migrations


def add_primary_emails(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    ProfileEmail = apps.get_model('profiles', 'ProfileEmail')
    for profile in Profile.objects.all():
        ProfileEmail.objects.get_or_create(
            profile=profile,
            email=profile.email,
            defaults={'primary': True})


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profileemail_primary'),
    ]

    operations = [
        migrations.RunPython(add_primary_emails)
    ]
