# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-06 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20181002_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileemail',
            options={'ordering': ['-primary', '-still_valid', 'email']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
