# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-04 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileNonDuplicates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DifferentPeople', 'These are different people'), ('MultipleAllowed', 'Multiple Profiles allowed for this person')], max_length=32)),
                ('profiles', models.ManyToManyField(to='profiles.Profile')),
            ],
        ),
    ]
