# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_profilenonduplicates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilenonduplicates",
            options={
                "verbose_name": "Profile non-duplicates",
                "verbose_name_plural": "Profile non-duplicates",
            },
        ),
    ]
