# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-18 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20181118_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='webpage',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
