# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_affiliation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affiliation",
            options={
                "ordering": ["profile__last_name", "profile__first_name", "date_until"]
            },
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="category",
            field=models.CharField(
                choices=[
                    ("employed_prof_full", "Full Professor"),
                    ("employed_prof_associate", "Associate Professor"),
                    ("employed_prof_assistant", "Assistant Professor"),
                    ("employed_prof_emeritus", "Emeritus Professor"),
                    ("employed_permanent_staff", "Permanent Staff"),
                    ("employed_fixed_term_staff", "Fixed Term Staff"),
                    ("employed_tenure_track", "Tenure Tracker"),
                    ("employed_postdoc", "Postdoctoral Researcher"),
                    ("employed_phd", "PhD candidate"),
                    ("associate_scientist", "Associate Scientist"),
                    ("consultant", "Consultant"),
                    ("visitor", "Visitor"),
                ],
                help_text="Select the most suitable category",
                max_length=64,
            ),
        ),
    ]
