# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-29 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0020_auto_20190327_1713"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="category",
            field=models.CharField(
                choices=[
                    ("employed_prof_full", "Full Professor"),
                    ("employed_prof_associate", "Associate Professor"),
                    ("employed_prof_assistant", "Assistant Professor"),
                    ("employed_prof_emeritus", "Emeritus Professor"),
                    ("employed_permanent_staff", "Permanent Staff"),
                    ("employed_fixed_term_staff", "Fixed Term Staff"),
                    ("employed_tenure_track", "Tenure Tracker"),
                    ("employed_postdoc", "Postdoctoral Researcher"),
                    ("employed_phd", "PhD candidate"),
                    ("associate_scientist", "Associate Scientist"),
                    ("consultant", "Consultant"),
                    ("visitor", "Visitor"),
                    ("unspecified", "Unspecified"),
                ],
                default="unspecified",
                help_text="Select the most suitable category",
                max_length=64,
            ),
        ),
    ]
