# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-31 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_auto_20190329_0744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
