# Generated by Django 3.2.18 on 2023-12-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_alter_profile_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
