# Generated by Django 3.2.5 on 2021-10-06 10:01

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0035_alter_profile_title"),
    ]

    operations = [
        UnaccentExtension(),
    ]
