# Generated by Django 3.2.18 on 2023-12-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orcid_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
