# Generated by Django 4.2.10 on 2024-03-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0038_auto_20240220_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileemail",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
    ]
