# Generated by Django 4.2.10 on 2024-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0039_alter_profileemail_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name_original",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name in original script (if not using the Latin alphabet)",
                max_length=64,
                verbose_name="First name (original)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name_original",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name in original script (if not using the Latin alphabet)",
                max_length=64,
                verbose_name="Last name (original)",
            ),
        ),
    ]
