# Generated by Django 4.2.10 on 2024-08-15 16:58

import secrets
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0041_profile_orcid_authenticated"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileemail",
            name="token_expiration",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name="profileemail",
            name="verification_token",
            field=models.CharField(max_length=128, null=True, unique=False),
        ),
    ]
