# Generated by Django 4.2.15 on 2024-08-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0042_profileemail_token_expiration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name_original",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: Name in non-Latin alphabet",
                max_length=64,
                verbose_name="First name (original)",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name_original",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: Name in non-Latin alphabet",
                max_length=64,
                verbose_name="Last name (original)",
            ),
        ),
    ]
