# Generated by Django 5.0.12 on 2025-03-20 13:45

from django.db import migrations, models


def toggle_is_anonymous(apps, schema_editor):
    """
    Set is_anonymous to True for all profiles with a first name == "Anonymous".
    """
    Profile = apps.get_model("profiles", "Profile")
    Profile.objects.filter(first_name="Anonymous").update(is_anonymous=True)
    Profile.objects.exclude(first_name="Anonymous").update(is_anonymous=False)


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0043_alter_profile_first_name_original_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(toggle_is_anonymous, migrations.RunPython.noop),
    ]
