# Generated by Django 5.0.12 on 2025-06-18 07:24

from django.db import migrations, models


def create_recovery_email_from_user(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    ProfileEmail = apps.get_model("profiles", "ProfileEmail")

    for profile in Profile.objects.filter(contributor__dbuser__isnull=False):
        # Create a new ProfileEmail for the recovery email
        email, created = ProfileEmail.objects.get_or_create(
            profile=profile,
            email=profile.contributor.dbuser.email,
            defaults={
                "kind": "recovery",
                "primary": False,
                "verified": True,
                "still_valid": True,
                "added_by": profile.contributor,
            },
        )

        if not created:
            # If the email already exists, update the kind to recovery
            email.kind = "recovery"
            email.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0045_profile_is_anonymous"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileemail",
            name="kind",
            field=models.CharField(
                choices=[("communication", "Communication"), ("recovery", "Recovery")],
                default="communication",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            create_recovery_email_from_user,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
