# Generated by Django 5.0.12 on 2025-08-04 11:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mails", "0010_mailaddressdomain"),
        ("profiles", "0047_profileemail_domain"),
        ("scipost", "0045_alter_totpdevice_token"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="profileemail",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="profileemail",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_profile_email",
                violation_error_message="The email address is already associated with a profile.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profileemail",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("email__regex", "^[\\w\\.\\-\\'\\+]+@[\\w\\.\\-]+\\.[a-zA-Z]{2,}$")
                ),
                name="valid_email_format",
                violation_error_message="Email must be in a valid format.",
            ),
        ),
    ]
