# Generated by Django 5.2.5 on 2025-08-06 09:53

import django.contrib.postgres.lookups
import django.db.models.functions.text
from django.db import migrations, models

from common.utils.lookups import ImmutableUnaccent


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_add_immutable_unaccent_function"),
        ("profiles", "0048_alter_profileemail_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    "first_name", models.Value(" "), "last_name"
                ),
                output_field=models.CharField(max_length=128),
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name_original",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    "first_name_original", models.Value(" "), "last_name_original"
                ),
                output_field=models.CharField(max_length=128),
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name_normalized",
            field=models.GeneratedField(
                db_persist=True,
                expression=ImmutableUnaccent(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.text.Concat(
                            "first_name", models.Value(" "), "last_name"
                        )
                    )
                ),
                output_field=models.CharField(max_length=128),
            ),
        ),
    ]
