# Generated by Django 5.2.5 on 2025-10-03 14:47

from django.db import migrations

from merger.models import NonDuplicateMark
from scipost.models import Contributor


def create_marks_from_profile_non_duplicates(apps, schema_editor):
    ProfileNonDuplicates = apps.get_model("profiles", "ProfileNonDuplicates")

    system = Contributor.objects.get(dbuser__username="system")

    marks: list[NonDuplicateMark] = []
    for non_duplicate in ProfileNonDuplicates.objects.all():
        profiles = list(non_duplicate.profiles.all())
        if len(profiles) < 2:
            continue

        marks.extend(
            NonDuplicateMark.from_objects(
                *profiles,
                marked_by=system,
                description=non_duplicate.get_reason_display() or "",
            )
        )

    NonDuplicateMark.objects.bulk_create(marks, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("merger", "0001_initial"),
        ("profiles", "0049_profile_full_name_profile_full_name_original_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_marks_from_profile_non_duplicates, migrations.RunPython.noop
        ),
        migrations.DeleteModel(name="ProfileNonDuplicates"),
    ]
