# Generated by Django 5.2.5 on 2025-10-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0050_create_nonduplicatemarks_from_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileemail",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="profileemail",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
