# Generated by Django 5.2.5 on 2026-03-09 10:42

import common.utils.lookups
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0051_profileemail_created_profileemail_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="full_name_normalized",
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name_normalized",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Lower(
                    common.utils.lookups.ImmutableUnaccent(
                        django.db.models.functions.text.Concat(
                            "first_name", models.Value(" "), "last_name"
                        )
                    )
                ),
                output_field=models.CharField(max_length=128),
            ),
        ),
    ]
