# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commentaries', '0001_initial'),
        ('scipost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors_com', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='authors_claims',
            field=models.ManyToManyField(blank=True, related_name='authors_com_claims', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='authors_false_claims',
            field=models.ManyToManyField(blank=True, related_name='authors_com_false_claims', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='vetted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor'),
        ),
    ]
