# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0002_auto_20160329_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='arxiv_or_DOI_string',
            field=models.CharField(default='', max_length=100, verbose_name='string form of arxiv nr or DOI for commentary url'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of original publication'),
        ),
    ]
