# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0003_auto_20160401_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name_plural': 'Commentaries'},
        ),
    ]
