# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0005_auto_20160420_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='journal',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='commentary',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commentary',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
