# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 13:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0006_auto_20160422_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='arxiv_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='arXiv identifier (including version nr)'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='commentary',
            name='pub_DOI',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='DOI of the original publication'),
        ),
    ]
