# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0007_auto_20160422_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='type',
            field=models.CharField(choices=[('published', 'published paper'), ('preprint', 'arXiv preprint')], max_length=9),
        ),
    ]
