# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import scipost.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0013_auto_20161213_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='latest_activity',
            field=scipost.db.fields.AutoDateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
