# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0015_auto_20170726_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='arxiv_identifier',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='arXiv identifier (including version nr)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentary',
            name='arxiv_or_DOI_string',
            field=models.CharField(default='', max_length=100, verbose_name='string form of arxiv nr or DOI for commentary url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentary',
            name='journal',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentary',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentary',
            name='pub_DOI',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='DOI of the original publication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentary',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
