# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-28 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0016_auto_20170726_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='pub_title',
            new_name='title',
        ),
    ]
