# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0018_auto_20170909_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='commentaries', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='authors_claims',
            field=models.ManyToManyField(blank=True, related_name='claimed_commentaries', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='authors_false_claims',
            field=models.ManyToManyField(blank=True, related_name='false_claimed_commentaries', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_commentaries', to='scipost.Contributor'),
        ),
    ]
