# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0052_auto_20171107_1354'),
        ('commentaries', '0019_auto_20170925_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='scipost_publication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentary', to='journals.Publication'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
