# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-16 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_prosfellow_to_potfellowship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectivefellow',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='prospectivefellowevent',
            name='noted_by',
        ),
        migrations.RemoveField(
            model_name='prospectivefellowevent',
            name='prosfellow',
        ),
        migrations.DeleteModel(
            name='ProspectiveFellow',
        ),
        migrations.DeleteModel(
            name='ProspectiveFellowEvent',
        ),
    ]
