# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0009_auto_20180916_2134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potentialfellowshipevent",
            name="noted_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
