# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-17 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0012_auto_20190114_0550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potentialfellowshipevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("defined", "Defined in database"),
                    ("nominated", "Nominated"),
                    ("votedon", "Voted on"),
                    ("elected", "Elected"),
                    ("emailed", "Emailed with invitation"),
                    ("responded", "Response received"),
                    ("statusupdated", "Status updated"),
                    ("comment", "Comment"),
                    ("deactivation", "Deactivation: not considered anymore"),
                ],
                max_length=32,
            ),
        ),
    ]
