# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-19 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0013_auto_20190117_1935"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fellowship",
            options={"ordering": ["contributor__user__last_name"]},
        ),
    ]
