# Generated by Django 2.2.11 on 2020-09-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0016_populate_colleges"),
    ]

    operations = [
        migrations.AddField(
            model_name="fellowship",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fellowships",
                to="colleges.College",
            ),
        ),
    ]
