# Generated by Django 2.2.11 on 2020-09-06 12:25

from django.db import migrations


def assign_college(apps, schema_editor):
    College = apps.get_model('colleges.College')
    Fellowship = apps.get_model('colleges.Fellowship')

    for f in Fellowship.objects.all():
        college = College.objects.get(acad_field__slug=f.contributor.profile.discipline)
        f.college = college
        f.save()


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0017_fellowship_college'),
    ]

    operations = [
        migrations.RunPython(assign_college,
                             reverse_code=migrations.RunPython.noop),
    ]
