# Generated by Django 2.2.16 on 2020-09-25 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scipost", "0036_remove_authorshipclaim_publication"),
        ("colleges", "0019_auto_20200906_1436"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fellowship",
            unique_together={("college", "contributor", "start_date", "until_date")},
        ),
    ]
