# Generated by Django 2.2.16 on 2020-09-25 14:26

from django.db import migrations


def assign_college(apps, schema_editor):
    College = apps.get_model("colleges.College")
    PotentialFellowship = apps.get_model("colleges.PotentialFellowship")

    for f in PotentialFellowship.objects.all():
        college = College.objects.get(acad_field__slug=f.profile.discipline)
        f.college = college
        f.save()


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0021_potentialfellowship_college"),
    ]

    operations = [
        migrations.RunPython(assign_college, reverse_code=migrations.RunPython.noop),
    ]
