# Generated by Django 2.2.16 on 2020-09-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0022_potentialfellowship_set_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potentialfellowship",
            name="college",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="potential_fellowships",
                to="colleges.College",
            ),
        ),
    ]
