# Generated by Django 2.2.16 on 2020-09-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0023_auto_20200925_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
