# Generated by Django 2.2.16 on 2020-09-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0025_populate_college_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="college",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
