# Generated by Django 2.2.16 on 2021-03-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0027_auto_20200929_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowship',
            name='status',
            field=models.CharField(choices=[('regular', 'Regular'), ('senior', 'Senior'), ('guest', 'Guest')], default='regular', max_length=16),
        ),
    ]
