# Generated by Django 3.2.12 on 2022-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0034_alter_fellowshipnominationvotinground_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fellowshipnominationvote",
            constraint=models.UniqueConstraint(
                fields=("voting_round", "fellow"),
                name="unique_together_voting_round_fellow",
            ),
        ),
    ]
