# Generated by Django 3.2.12 on 2022-03-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0035_fellowshipnominationvote_unique_together_voting_round_fellow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellowshipnominationvote',
            name='comments',
        ),
        migrations.DeleteModel(
            name='FellowshipNominationEvent',
        ),
    ]
