# Generated by Django 3.2.12 on 2022-03-09 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def get_sentinel_user():
    """Temporary fix to be able to delete Contributor instances.

    Eventually the 'to-be-removed-Contributor' should be status: "deactivated" and anonymized.
    Fallback user for models relying on Contributor that is being deleted.
    """
    from django.contrib.auth import get_user_model
    from scipost.models import Contributor
    from scipost.constants import DISABLED

    user, __ = get_user_model().objects.get_or_create(username="deleted")
    return Contributor.objects.get_or_create(status=DISABLED, user=user)[0]


class Migration(migrations.Migration):
    dependencies = [
        ("scipost", "0040_auto_20210310_2026"),
        ("colleges", "0037_alter_fellowshipinvitation_postpone_start_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="FellowshipNominationEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(get_sentinel_user),
                        to="scipost.contributor",
                    ),
                ),
                (
                    "nomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="colleges.fellowshipnomination",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fellowhip Nomination Events",
                "ordering": ["nomination", "-on"],
            },
        ),
    ]
