# Generated by Django 3.2.18 on 2023-09-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0041_auto_20230720_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowshipnominationvotinground',
            name='voting_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fellowshipnominationvotinground',
            name='voting_opens',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
