# Generated by Django 3.2.18 on 2023-10-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0042_auto_20230914_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fellowshipnominationevent',
            options={'get_latest_by': 'on', 'ordering': ['nomination', '-on'], 'verbose_name_plural': 'Fellowhip Nomination Events'},
        ),
    ]
