# Generated by Django 3.2.18 on 2023-11-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0043_alter_fellowshipnominationevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowshipnominationdecision',
            name='outcome',
            field=models.CharField(choices=[('elected', 'Elected'), ('notelected', 'Not elected'), ('inconclusive', 'Inconclusive')], max_length=16),
        ),
    ]
