# Generated by Django 3.2.18 on 2024-02-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0045_move_vetoes_to_nomination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fellowshipinvitation',
            old_name='postpone_start_to',
            new_name='postponement_date',
        ),
        migrations.AlterField(
            model_name='fellowshipinvitation',
            name='response',
            field=models.CharField(blank=True, choices=[('notyetinvited', 'Not yet invited'), ('invited', 'Invited'), ('reinvited', 'Reinvited'), ('multireinvited', 'Multiply reinvited'), ('unresponsive', 'Unresponsive'), ('reinvitelater', 'Reinvite later'), ('accepted', 'Accepted, for immediate start'), ('postponed', 'Accepted, but start date postponed'), ('declined', 'Declined')], max_length=16),
        ),
    ]
