# Generated by Django 3.2.18 on 2024-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0046_rename_postponement_date_add_reinvite_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowshipnominationvotinground',
            name='type',
            field=models.CharField(choices=[('senior', 'Senior'), ('regular', 'Regular')], default='senior', max_length=16),
        ),
    ]
