# Generated by Django 5.0.12 on 2025-03-20 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colleges", "0047_fellowshipnominationvotinground_type"),
        ("scipost", "0043_rename_contributor_user_to_dbuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fellowship",
            options={"ordering": ["contributor__dbuser__last_name"]},
        ),
    ]
