# Generated by Django 5.0.12 on 2025-03-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0048_alter_fellowship_options_and_more"),
        ("scipost", "0044_alter_contributor_vetted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fellowshipnominationevent",
            name="by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scipost.contributor",
            ),
        ),
        migrations.AlterField(
            model_name="potentialfellowshipevent",
            name="noted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scipost.contributor",
            ),
        ),
    ]
