# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-23 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20190222_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ['last_name', 'first_name', 'organization']},
        ),
    ]
