# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commentaries', '0002_auto_20160329_2225'),
        ('comments', '0001_initial'),
        ('theses', '0001_initial'),
        ('submissions', '0001_initial'),
        ('scipost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.Commentary'),
        ),
        migrations.AddField(
            model_name='comment',
            name='in_agreement',
            field=models.ManyToManyField(related_name='in_agreement', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='in_disagreement',
            field=models.ManyToManyField(related_name='in_disagreement', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='in_notsure',
            field=models.ManyToManyField(related_name='in_notsure', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='in_reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='in_reply_to_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Report'),
        ),
        migrations.AddField(
            model_name='comment',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thesislink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theses.ThesisLink'),
        ),
    ]
