# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0003_auto_20160330_1104'),
        ('comments', '0002_auto_20160329_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_cor',
            field=models.BooleanField(default=False, verbose_name='correction'),
        ),
        migrations.AddField(
            model_name='comment',
            name='vetted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_vetted_by', to='scipost.Contributor'),
        ),
    ]
