# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171229_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='in_reply_to_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='in_reply_to_report',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thesislink',
        ),
    ]
