# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20160404_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='in_agreement',
            field=models.ManyToManyField(blank=True, related_name='in_agreement', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='in_disagreement',
            field=models.ManyToManyField(blank=True, related_name='in_disagreement', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='in_notsure',
            field=models.ManyToManyField(blank=True, related_name='in_notsure', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_cor',
            field=models.BooleanField(default=False, verbose_name='correction/erratum'),
        ),
    ]
