# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20161212_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='latest_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
