# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20161212_1931'),
        ('comments', '0004_auto_20161213_1208'),
    ]

    operations = [
    ]
