# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20170201_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='UPLOADS/COMMENTS/%Y/%m/'),
        ),
    ]
