# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 19:25
from __future__ import unicode_literals

import comments.behaviors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20170212_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file_attachment',
            field=models.FileField(blank=True, upload_to='comments/%Y/%m/%d/', validators=[comments.behaviors.validate_file_extension]),
        ),
    ]
