# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 09:06
from __future__ import unicode_literals

import comments.behaviors
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20170212_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file_attachment',
            field=models.FileField(blank=True, upload_to='uploads/comments/%Y/%m/%d/', validators=[comments.behaviors.validate_file_extension, comments.behaviors.validate_max_file_size]),
        ),
    ]
