# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20170326_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='submissions.Submission'),
        ),
    ]
