# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20170415_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_vet_comments', 'Can vet submitted Comments'),)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='remarks_for_editors',
            field=models.TextField(blank=True, verbose_name='optional remarks for the Editors only'),
        ),
    ]
