# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-28 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_auto_20170727_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='in_reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_comments_old', to='comments.Comment'),
        ),
    ]
