# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-29 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0017_auto_20170729_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentary',
            field=models.ForeignKey(blank=True, help_text='Warning: This field is out of service and will be removed in the future.', null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.Commentary'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(help_text='Warning: Rather use/edit `content_object` instead or be 100% sure you know what you are doing!', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='in_reply_to_comment',
            field=models.ForeignKey(blank=True, help_text='Warning: This field is out of service and will be removed in the future.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_comments_old', to='comments.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='in_reply_to_report',
            field=models.ForeignKey(blank=True, help_text='Warning: This field is out of service and will be removed in the future.', null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Report'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(help_text='Warning: Rather use/edit `content_object` instead or be 100% sure you know what you are doing!'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Warning: This field is out of service and will be removed in the future.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_old', to='submissions.Submission'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='thesislink',
            field=models.ForeignKey(blank=True, help_text='Warning: This field is out of service and will be removed in the future.', null=True, on_delete=django.db.models.deletion.CASCADE, to='theses.ThesisLink'),
        ),
    ]
