# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0018_auto_20170729_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='doi_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='needs_doi',
            field=models.NullBooleanField(default=None),
        ),
    ]
