# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0019_auto_20170909_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='doideposit_needs_updating',
            field=models.BooleanField(default=False),
        ),
    ]
