# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorReplyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('importance', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('clarity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('validity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('rigour', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentaryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('validity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('rigour', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('originality', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('significance', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('importance', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('clarity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('validity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('rigour', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('importance', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('clarity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('validity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('rigour', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('validity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('rigour', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('originality', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('significance', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThesisLinkRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('validity', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('rigour', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('originality', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
                ('significance', models.PositiveSmallIntegerField(choices=[(101, '-'), (100, 'top'), (80, 'high'), (60, 'good'), (40, 'ok'), (20, 'low'), (0, 'poor')], default=101)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
