# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0043_auto_20170512_0836'),
        ('scipost', '0054_delete_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('assigned_to_supervisor', 'Assigned to Supervisor'), ('officer_tasked_with_proof_production', 'Officer tasked with proofs production'), ('proofs_produced', 'Proofs have been produced'), ('proofs_sent_to_authors', 'Proofs sent to Authors'), ('proofs_returned_by_authors', 'Proofs returned by Authors'), ('corrections_implemented', 'Corrections implemented'), ('authors_have_accepted_proofs', 'Authors have accepted proofs')], max_length=64)),
                ('comments', models.TextField(blank=True, null=True)),
                ('noted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('noted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.DateTimeField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission')),
            ],
        ),
        migrations.AddField(
            model_name='productionevent',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ProductionStream'),
        ),
    ]
