# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20170528_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstream',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=32),
        ),
    ]
