# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-28 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productionstream_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstream',
            name='closed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
