# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_productionstream_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='noted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productionstream',
            name='opened',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
