# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-23 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20170610_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionevent',
            options={'ordering': ['noted_on']},
        ),
    ]
