# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-01 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20170623_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='noted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
