# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_productionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstream',
            name='officers',
            field=models.ManyToManyField(blank=True, to='production.ProductionUser'),
        ),
    ]
