# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_productionstream_officers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionevent',
            old_name='noted_by',
            new_name='noted_by_contributor',
        ),
        migrations.AlterField(
            model_name='productionstream',
            name='officers',
            field=models.ManyToManyField(blank=True, related_name='streams', to='production.ProductionUser'),
        ),
        migrations.AlterField(
            model_name='productionuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='production_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
