# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_auto_20170914_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionevent',
            name='noted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.ProductionUser'),
            preserve_default=False,
        ),
    ]
