# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_auto_20170914_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='noted_by_contributor',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor'),
        ),
        migrations.RemoveField(
            model_name='productionevent',
            name='noted_by_contributor',
        ),
    ]
