# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_auto_20170914_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionevent',
            name='noted_by_contributor',
        ),
    ]
