# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_remove_productionevent_noted_by_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='production.ProductionStream'),
        ),
    ]
