# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_auto_20170914_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstream',
            name='officers',
        ),
        migrations.AddField(
            model_name='productionstream',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='production.ProductionUser'),
        ),
        migrations.AddField(
            model_name='productionstream',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_streams', to='production.ProductionUser'),
        ),
    ]
