# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_auto_20170929_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionstream',
            options={'permissions': (('can_perform_supervisory_actions', 'Can perform supervisory actions'),)},
        ),
    ]
