# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_auto_20170929_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionstream',
            options={'permissions': (('can_work_for_stream', 'Can work for stream'), ('can_perform_supervisory_actions', 'Can perform supervisory actions'))},
        ),
        migrations.AlterField(
            model_name='productionevent',
            name='noted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='production.ProductionUser'),
        ),
    ]
