# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_auto_20170930_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionstream',
            options={'permissions': (('can_work_for_stream', 'Can work for stream'),)},
        ),
    ]
