# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_auto_20170930_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionevent',
            name='noted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_events', to='production.ProductionUser'),
        ),
        migrations.AlterField(
            model_name='productionevent',
            name='event',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('message_edadmin_to_supervisor', 'Message from EdAdmin to Supervisor'), ('message_supervisor_to_edadmin', 'Message from Supervisor to EdAdmin'), ('officer_tasked_with_proof_production', 'Supervisor tasked officer with proofs production'), ('message_supervisor_to_officer', 'Message from Supervisor to Officer'), ('message_officer_to_supervisor', 'Message from Officer to Supervisor'), ('proofs_produced', 'Proofs have been produced'), ('proofs_checked_by_supervisor', 'Proofs have been checked by Supervisor'), ('proofs_sent_to_authors', 'Proofs sent to Authors'), ('proofs_returned_by_authors', 'Proofs returned by Authors'), ('corrections_implemented', 'Corrections implemented'), ('authors_have_accepted_proofs', 'Authors have accepted proofs'), ('paper_published', 'Paper has been published'), ('cited_notified', 'Cited people have been notified/invited to SciPost')], max_length=64),
        ),
    ]
