# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_auto_20171003_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionstream',
            options={'permissions': (('can_work_for_stream', 'Can work for stream'), ('can_perform_supervisory_actions', 'Can perform supervisory actions'))},
        ),
    ]
