# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_auto_20170930_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='event',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('status', 'Status change'), ('message', 'Message'), ('registration', 'Registration hours')], max_length=64),
        ),
    ]
