# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_auto_20170930_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='upload_by',
        ),
        migrations.AddField(
            model_name='proof',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='production.ProductionUser'),
            preserve_default=False,
        ),
    ]
