# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_auto_20170930_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='accessible_for_authors',
            field=models.BooleanField(default=False),
        ),
    ]
