# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_auto_20171003_1525'),
        ('production', '0026_proof_accessible_for_authors'),
    ]

    operations = [
    ]
