# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_merge_20171004_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proof',
            options={'ordering': ['stream', 'version']},
        ),
        migrations.AlterField(
            model_name='proof',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Proofs uploaded'), ('sent', 'Proofs sent to authors'), ('accepted_sup', 'Proofs accepted by supervisor'), ('declined_sup', 'Proofs declined by supervisor'), ('accepted', 'Proofs accepted by authors'), ('declined', 'Proofs declined by authors'), ('renewed', 'Proofs renewed')], default='uploaded', max_length=16),
        ),
    ]
