# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_auto_20171007_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstream',
            name='invitations_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_officer_streams', to='production.ProductionUser'),
        ),
    ]
