# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_productionstream_invitations_officer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proof',
            new_name='Proofs',
        ),
    ]
