# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_auto_20171009_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proofs',
            options={'ordering': ['stream', 'version'], 'verbose_name_plural': 'Proofs'},
        ),
    ]
