# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import production.models
import scipost.storage


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_auto_20171010_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEventAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(storage=scipost.storage.SecureFileStorage(), upload_to=production.models.production_event_upload_location)),
                ('production_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='production.ProductionEvent')),
            ],
        ),
    ]
