# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-25 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funders", "0005_auto_20180425_2211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="further_details",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="grant",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
