# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0007_funder_organization'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='funder',
        #     name='organization',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Organization'),
        # ),
    ]
