# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funders", "0010_repopulate_funder_orgs"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='funder',
        #     name='organization',
        # ),
    ]
