# Generated by Django 3.2.18 on 2023-08-25 09:01

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):
    dependencies = [
        ("funders", "0013_auto_20190518_1304"),
    ]

    operations = [
        UnaccentExtension(),
    ]
