# Generated by Django 4.2.10 on 2024-03-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0040_auto_20210310_2026"),
        ("funders", "0014_enable_unaccent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="funder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="funders.funder"
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scipost.contributor",
            ),
        ),
    ]
