# Generated by Django 4.2.10 on 2024-04-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_auto_20180706_1459"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewsLetter",
            new_name="NewsCollection",
        ),
        migrations.RenameModel(
            old_name="NewsLetterNewsItemsTable",
            new_name="NewsCollectionNewsItemsTable",
        ),
        migrations.RenameField(
            model_name="newscollectionnewsitemstable",
            old_name="newsletter",
            new_name="newscollection",
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="blurb_short",
            field=models.TextField(
                default="",
                help_text="Short version for use in NewsCollection/emails etc",
            ),
        ),
    ]
