# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitionsignatory',
            options={'verbose_name_plural': 'petition signatories'},
        ),
    ]
