# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_auto_20171004_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitionsignatory',
            options={'ordering': ['last_name', 'country_of_employment', 'affiliation'], 'verbose_name_plural': 'petition signatories'},
        ),
        migrations.AlterField(
            model_name='petitionsignatory',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_signatories', to='petitions.Petition'),
        ),
        migrations.AlterField(
            model_name='petitionsignatory',
            name='signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_signatories', to='scipost.Contributor'),
        ),
    ]
