# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_auto_20171004_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='preamble',
            field=models.TextField(blank=True, null=True),
        ),
    ]
