# Generated by Django 2.2.16 on 2020-09-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0014_auto_20200926_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesislink',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='thesislink',
            name='subject_area',
        ),
    ]
