# Generated by Django 5.2.5 on 2026-03-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theses", "0016_alter_thesislink_approaches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesislink",
            name="vetted",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
