# Generated by Django 2.1.8 on 2019-06-23 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_auto_20180519_1313"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="in_agreement",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="in_disagreement",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="in_notsure",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="nr_A",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="nr_D",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="nr_N",
        ),
    ]
