# Generated by Django 3.2.5 on 2021-07-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20190623_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='needs_doi',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
