# Generated by Django 3.2.5 on 2021-10-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_needs_doi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_submitted'], 'permissions': (('can_vet_comments', 'Can vet submitted Comments'),)},
        ),
    ]
