# Generated by Django 5.2.5 on 2026-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_alter_comment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Vetted"),
                    (0, "Not yet vetted (pending)"),
                    (-1, "Rejected (unclear)"),
                    (-2, "Rejected (incorrect)"),
                    (-3, "Rejected (not useful)"),
                    (-4, "Rejected (duplicate)"),
                ],
                default=0,
            ),
        ),
    ]
