# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scipost.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scipost', '0065_authorshipclaim_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialCollegeFellowship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_activity', scipost.db.fields.AutoDateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('until_date', models.DateField(blank=True, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowships', to='scipost.Contributor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='editorialcollegefellowship',
            unique_together=set([('contributor', 'start_date', 'until_date')]),
        ),
    ]
