# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 07:31
from __future__ import unicode_literals

from django.db import migrations


def fill_editorial_college(apps, schema_editor):
    Fellowship = apps.get_model('colleges', 'Fellowship')
    Contributor = apps.get_model('scipost', 'Contributor')
    for contributor in Contributor.objects.filter(user__groups__name='Editorial College'):
        Fellowship.objects.get_or_create(contributor=contributor)


def return_empty(*args, **kwargs):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_editorial_college, return_empty),
    ]
