# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20171014_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditorialCollegeFellowship',
            new_name='Fellowship',
        ),
    ]
