# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20171014_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellowship',
            name='affiliation',
        ),
    ]
