# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0003_auto_20180117_2323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="accepted_submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication",
                to="submissions.Submission",
            ),
        ),
    ]
