# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0004_auto_20180122_2109"),
        ("journals", "0005_auto_20180122_1003"),
    ]

    operations = []
