# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0007_auto_20180129_1814"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reference",
            old_name="vor",
            new_name="identifier",
        ),
        migrations.RenameField(
            model_name="reference",
            old_name="vor_url",
            new_name="link",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="title",
        ),
        migrations.AlterField(
            model_name="reference",
            name="authors",
            field=models.CharField(max_length=1028),
        ),
        migrations.AlterField(
            model_name="reference",
            name="citation",
            field=models.CharField(blank=True, max_length=1028),
        ),
    ]
