# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0012_auto_20180212_1950"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="authors_old",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="authors_unregistered_old",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="first_author",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="first_author_unregistered",
        ),
    ]
