# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0020_auto_20180310_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='has_volumes',
            field=models.BooleanField(default=True, verbose_name='Use Volumes to group Publications'),
        ),
    ]
