# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0022_auto_20180310_1154"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="structure",
            field=models.CharField(
                choices=[
                    ("IV", "Issues and Volumes"),
                    ("IO", "Issues only"),
                    ("IP", "Individual Publications"),
                ],
                default="IV",
                max_length=2,
            ),
        ),
    ]
