# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0025_auto_20180314_1637"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volume",
            options={"ordering": ("-until_date",)},
        ),
    ]
