# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0027_auto_20180414_1627"),
        ("journals", "0027_auto_20180414_2053"),
    ]

    operations = []
