# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0027_auto_20180414_2053"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="number_of_citations",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
