# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0028_publication_number_of_citations'),
        ('journals', '0028_merge_20180426_1023'),
    ]

    operations = [
    ]
