# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0028_publication_number_of_citations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="number_of_citations",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
