# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0029_auto_20180519_1658"),
        ("journals", "0029_merge_20180519_1308"),
    ]

    operations = []
