# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0036_auto_20180918_1723"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="pubfractions_confirmed_by_authors",
            field=models.BooleanField(default=False),
        ),
    ]
