# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_populate_from_partners_org"),
        ("journals", "0037_publication_pubfractions_confirmed_by_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgpubfraction",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pubfractions",
                to="organizations.Organization",
            ),
        ),
        migrations.AddField(
            model_name="publicationauthorstable",
            name="affs",
            field=models.ManyToManyField(blank=True, to="organizations.Organization"),
        ),
    ]
