# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 18:50
from __future__ import unicode_literals

from django.db import migrations


def update_issue_slugs(apps, schema_editor):
    """Fill all slug fields for existing Issue instances."""
    Issue = apps.get_model('journals', 'Issue')

    for issue in Issue.objects.all():
        Issue.objects.filter(id=issue.id).update(slug=issue.number)


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0043_auto_20180927_2014'),
    ]

    operations = [
        migrations.RunPython(update_issue_slugs),
    ]
