# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0048_auto_20181023_2150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="name",
            field=models.CharField(
                choices=[
                    ("SciPostPhys", "SciPost Physics"),
                    ("SciPostPhysLectNotes", "SciPost Physics Lecture Notes"),
                    ("SciPostPhysProc", "SciPost Physics Proceedings"),
                    ("SciPostPhysComm", "SciPost Physics Commons"),
                    ("SciPostPhysCodeb", "SciPost Physics Codebases"),
                    ("SciPostPhysSel", "SciPost Physics Select"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
