# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0022_auto_20190331_1926"),
        ("journals", "0055_auto_20190126_2058"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationauthorstable",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.Profile",
            ),
        ),
    ]
