# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0057_remove_publication_institutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unregisteredauthor',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors_unregistered',
        ),
        migrations.RemoveField(
            model_name='publicationauthorstable',
            name='unregistered_author',
        ),
        migrations.DeleteModel(
            name='UnregisteredAuthor',
        ),
    ]
