# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0058_auto_20190404_1949"),
        ("journals", "0057_auto_20190404_1738"),
    ]

    operations = []
