# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-05 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0060_remove_publication_authors_registered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicationauthorstable",
            name="contributor",
        ),
    ]
