# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-25 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0061_remove_publicationauthorstable_contributor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationProxyMetadata",
            fields=[],
            options={
                "indexes": [],
                "proxy": True,
                "verbose_name_plural": "Publication metadata",
                "verbose_name": "Publication metadata",
            },
            bases=("journals.publication",),
        ),
    ]
