# Generated by Django 2.0.13 on 2019-05-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0062_publicationproxymetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="in_journal",
            field=models.ForeignKey(
                blank=True,
                help_text="Assign either a Volume or Journal to the Issue",
                limit_choices_to={"structure": "IO"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="journals.Journal",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="in_journal",
            field=models.ForeignKey(
                limit_choices_to={"structure": "IV"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volumes",
                to="journals.Journal",
            ),
        ),
    ]
