# Generated by Django 2.1.8 on 2019-05-18 11:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0063_auto_20190512_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'default_related_name': 'issues', 'ordering': ('-until_date',)},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'default_related_name': 'publications', 'ordering': ('-publication_date', '-paper_nr')},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'default_related_name': 'references', 'ordering': ['reference_number']},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'default_related_name': 'volumes', 'ordering': ('-until_date',)},
        ),
        migrations.AlterField(
            model_name='publication',
            name='citedby',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='metadata_DOAJ',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
