# Generated by Django 2.1.8 on 2019-09-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0067_journal_name_abbrev"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("publicly_open", "Publicly open"),
                    ("published", "Published"),
                ],
                default="published",
                max_length=20,
            ),
        ),
    ]
