# Generated by Django 2.1.8 on 2019-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0077_auto_20190924_1027"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="blurb",
            field=models.TextField(default="[To be filled in; you can use markup]"),
        ),
    ]
