# Generated by Django 2.2.11 on 2020-05-02 04:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import journals.models.journal


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0085_auto_20191017_0949"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="cost_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=journals.models.journal.cost_default_value
            ),
        ),
    ]
