# Generated by Django 2.2.11 on 2020-07-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0088_auto_20200707_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="submission_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
