# Generated by Django 2.2.16 on 2020-09-26 05:21

from django.db import migrations


def populate_journal_specialties(apps, schema_editor):
    Journal = apps.get_model("journals.Journal")

    for journal in Journal.objects.all():
        journal.specialties.set(journal.college.acad_field.specialties.all())


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0095_auto_20200924_2044"),
    ]

    operations = [
        migrations.RunPython(
            populate_journal_specialties, reverse_code=migrations.RunPython.noop
        ),
    ]
