# Generated by Django 2.2.16 on 2020-09-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0007_Branch_Field_Specialty"),
        ("journals", "0096_journal_specialties"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="acad_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publications",
                to="ontology.AcademicField",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="specialties",
            field=models.ManyToManyField(
                blank=True, related_name="publications", to="ontology.Specialty"
            ),
        ),
    ]
