# Generated by Django 2.2.16 on 2020-09-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0099_auto_20200926_2228"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="secondary_areas",
        ),
    ]
