# Generated by Django 2.2.16 on 2020-09-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0100_remove_publication_secondary_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['college__acad_field', 'list_order']},
        ),
        migrations.RemoveField(
            model_name='journal',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='subject_area',
        ),
    ]
