# Generated by Django 2.2.16 on 2021-01-14 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0104_auto_20201026_2144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="doi_label",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((SciPost)[a-zA-Z]+|(MigPol))\\.\\w$",
                        "Only expressions with regex ((SciPost)[a-zA-Z]+|(MigPol))\\.\\w are allowed.",
                    )
                ],
            ),
        ),
    ]
