# Generated by Django 3.0.14 on 2021-07-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0108_journal_oneliner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationupdate',
            name='update_type',
            field=models.CharField(choices=[('addendum', 'Addendum'), ('clarification', 'Clarification'), ('correction', 'Correction'), ('corrigendum', 'Corrigendum'), ('erratum', 'Erratum'), ('expression_of_concern', 'Expression of concern'), ('new_edition', 'New edition'), ('new_version', 'New version'), ('partial_retraction', 'Partial_retraction'), ('removal', 'Removal'), ('retraction', 'Retraction'), ('withdrawal', 'Withdrawal')], default='correction', max_length=32),
        ),
    ]
