# Generated by Django 3.2.5 on 2021-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0112_submissiontemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontemplate",
            name="instructions",
            field=models.TextField(default="[To be filled in; you can use markup]"),
        ),
    ]
