# Generated by Django 3.2.12 on 2022-02-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0114_journal_required_article_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='cf_citation',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
