# Generated by Django 3.2.14 on 2022-08-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0121_remove_publication_bibtex_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutogeneratedFileContentTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=128)),
                (
                    "content_template_string",
                    models.TextField(help_text="Python template string"),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journals.journal",
                    ),
                ),
            ],
            options={
                "ordering": ["journal__doi_label", "name"],
            },
        ),
    ]
