# Generated by Django 3.2.14 on 2022-08-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0122_autogeneratedfilecontenttemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_type",
                    models.CharField(
                        choices=[
                            ("source_repo", "Publication source files repository"),
                            (
                                "release_repo",
                                "Codebase release version (archive) repository",
                            ),
                            ("live_repo", "Live (external) repository"),
                        ],
                        max_length=32,
                    ),
                ),
                ("url", models.URLField()),
                ("comments", models.CharField(blank=True, max_length=256)),
                ("deprecated", models.BooleanField(default=False)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="journals.publication",
                    ),
                ),
            ],
        ),
    ]
