# Generated by Django 3.2.14 on 2022-08-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0123_publicationresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="has_CLOCKSS",
            field=models.BooleanField(default=True),
        ),
    ]
