# Generated by Django 3.2.16 on 2023-01-21 13:29

from django.db import migrations, models
import journals.constants


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0126_populate_journal_publishable_object_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='submission_object_types',
            field=models.JSONField(default=journals.constants.get_submission_object_types_default),
        ),
    ]
