# Generated by Django 4.2.10 on 2024-03-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0129_alter_issue_in_journal_alter_issue_in_volume_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="pubfractions_confirmed_by_authors",
        ),
    ]
