# Generated by Django 4.2.10 on 2024-04-17 10:05

from django.db import migrations, models
import journals.constants


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0131_alter_journal_acceptance_criteria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="acceptance_criteria",
            field=models.JSONField(
                default=journals.constants.get_default_acceptance_criteria
            ),
        ),
    ]
