# Generated by Django 4.2.10 on 2024-07-04 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0132_alter_journal_acceptance_criteria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="doi_label",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((SciPost)[a-zA-Z]+|(MigPol))\\.\\w+$",
                        "Only expressions with regex ((SciPost)[a-zA-Z]+|(MigPol))\\.\\w+ are allowed.",
                    )
                ],
            ),
        ),
    ]
