# Generated by Django 4.2.10 on 2024-08-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0133_alter_volume_doi_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="alternative_journals",
            field=models.ManyToManyField(to="journals.journal"),
        ),
    ]
