# Generated by Django 4.2.15 on 2024-10-25 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0138_journal_assignment_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="assignment_period",
            field=models.DurationField(default=datetime.timedelta(days=56)),
        ),
    ]
