# Generated by Django 4.2.15 on 2024-12-23 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0139_alter_journal_assignment_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="doi_label",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((SciPost)[a-zA-Z]+|(MigPol|RobustRep))\\.\\w+(\\.[0-9]+)?$",
                        "Only expressions with regex ((SciPost)[a-zA-Z]+|(MigPol|RobustRep))\\.\\w+(\\.[0-9]+)? are allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="doi_label",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(SciPost)[a-zA-Z]+|(MigPol|RobustRep)$",
                        "Only expressions with regex (SciPost)[a-zA-Z]+|(MigPol|RobustRep) are allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="doi_label",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((SciPost)[a-zA-Z]+|(MigPol|RobustRep))(\\.\\w+(\\.[0-9]+(\\.[0-9]{3,})?)?)?(-r[0-9]+(\\.[0-9]+)?)?$",
                        "Only expressions with regex ((SciPost)[a-zA-Z]+|(MigPol|RobustRep))(\\.\\w+(\\.[0-9]+(\\.[0-9]{3,})?)?)?(-r[0-9]+(\\.[0-9]+)?)? are allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="doi_label",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((SciPost)[a-zA-Z]+|(MigPol|RobustRep))\\.\\w+$",
                        "Only expressions with regex ((SciPost)[a-zA-Z]+|(MigPol|RobustRep))\\.\\w+ are allowed.",
                    )
                ],
            ),
        ),
    ]
