# Generated by Django 5.2.5 on 2026-03-09 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0140_alter_issue_doi_label_alter_journal_doi_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="doi_label",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((SciPost[a-zA-Z]+|MigPol|JRobustRep|JSocBehavCh))\\.\\w+(\\.[0-9]+)?$",
                        "Only expressions with regex ((SciPost[a-zA-Z]+|MigPol|JRobustRep|JSocBehavCh))\\.\\w+(\\.[0-9]+)? are allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="doi_label",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(SciPost[a-zA-Z]+|MigPol|JRobustRep|JSocBehavCh)$",
                        "Only expressions with regex (SciPost[a-zA-Z]+|MigPol|JRobustRep|JSocBehavCh) are allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="doi_label",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((SciPost[a-zA-Z]+|MigPol|JRobustRep|JSocBehavCh))(\\.(\\w+)(\\.(\\d+)(\\.(\\d{3,}))?)?)?(-([rv]\\d+(\\.\\d+)?|\\w+))?$",
                        "Only expressions with regex ((SciPost[a-zA-Z]+|MigPol|JRobustRep|JSocBehavCh))(\\.(\\w+)(\\.(\\d+)(\\.(\\d{3,}))?)?)?(-([rv]\\d+(\\.\\d+)?|\\w+))? are allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="doi_label",
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((SciPost[a-zA-Z]+|MigPol|JRobustRep|JSocBehavCh))\\.\\w+$",
                        "Only expressions with regex ((SciPost[a-zA-Z]+|MigPol|JRobustRep|JSocBehavCh))\\.\\w+ are allowed.",
                    )
                ],
            ),
        ),
    ]
