# Generated by Django 5.2.5 on 2026-03-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0141_alter_issue_doi_label_alter_journal_doi_label_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicationresource",
            options={"ordering": ["-publication", "_type"]},
        ),
    ]
