# Generated by Django 5.2.5 on 2026-04-09 13:39

from django.db import migrations, models

KEY_MAP = {
    "prepub": "prepublished",
    "pub": "published",
}


def update_publication_status_keys(key_map: dict[str, str]):

    def update(apps, schema_editor):
        Publication = apps.get_model("journals", "Publication")
        for old_key, new_key in key_map.items():
            Publication.objects.filter(status=old_key).update(status=new_key)

    def reverse_update(apps, schema_editor):
        Publication = apps.get_model("journals", "Publication")
        for new_key, old_key in key_map.items():
            Publication.objects.filter(status=new_key).update(status=old_key)

    return update, reverse_update


class Migration(migrations.Migration):
    dependencies = [
        ("journals", "0142_alter_publicationresource_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("prepublished", "Pre-published"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.RunPython(*update_publication_status_keys(KEY_MAP)),
    ]
