# Generated by Django 5.2.5 on 2026-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0143_alter_publication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="current_revision_description",
            field=models.TextField(
                blank=True,
                help_text="Details about the current revision process, if applicable.",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("prepublished", "Pre-published"),
                    ("published", "Published"),
                    ("under_revision", "Under revision"),
                    ("retracted", "Retracted"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={
                "default_related_name": "publications",
                "get_latest_by": "publication_date",
                "ordering": ("-publication_date", "-paper_nr", "pubtype"),
            },
        ),
    ]
