# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0002_auto_20171229_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
