# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0003_auto_20180206_1940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
