# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0005_auto_20180218_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationinvitation',
            options={},
        ),
    ]
