# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scipost", "0007_auto_20180318_1336"),
        ("scipost", "0007_auto_20180314_1502"),
    ]

    operations = []
