# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scipost", "0007_auto_20180313_1741"),
        ("scipost", "0008_merge_20180322_1031"),
    ]

    operations = []
