# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0009_merge_20180322_2120"),
        ("scipost", "0009_auto_20180327_1933"),
    ]

    operations = []
