# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-14 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scipost", "0013_remove_contributor_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributor",
            old_name="new_status",
            new_name="status",
        ),
    ]
