# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-15 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scipost", "0016_auto_20180930_1801"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contributor",
            options={"ordering": ["user__last_name", "user__first_name"]},
        ),
    ]
