# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-15 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0018_contributor_duplicate_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="personalwebpage",
            field=models.URLField(
                blank=True, max_length=300, verbose_name="personal web page"
            ),
        ),
    ]
