# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-05 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0023_totpdevice'),
    ]

    operations = [
        # Deprec virtualmeetings 2019-04-05
        # migrations.RemoveField(
        #     model_name='remark',
        #     name='feedback',
        # ),
        # migrations.RemoveField(
        #     model_name='remark',
        #     name='motion',
        # ),
        # migrations.RemoveField(
        #     model_name='remark',
        #     name='nomination',
        # ),
    ]
