# Generated by Django 2.1.8 on 2019-05-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0024_auto_20190405_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'default_related_name': 'remarks', 'ordering': ['date']},
        ),
    ]
