# Generated by Django 2.1.8 on 2019-08-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0026_auto_20190522_1120"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="totpdevice",
            options={"default_related_name": "devices", "verbose_name": "TOTP Device"},
        ),
    ]
