# Generated by Django 2.1.8 on 2019-08-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0027_auto_20190826_0924'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='editorialcollegefellowship',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='editorialcollegefellowship',
            name='college',
        ),
        migrations.RemoveField(
            model_name='editorialcollegefellowship',
            name='contributor',
        ),
        migrations.DeleteModel(
            name='EditorialCollege',
        ),
        migrations.DeleteModel(
            name='EditorialCollegeFellowship',
        ),
    ]
