# Generated by Django 2.2.16 on 2020-09-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0036_remove_authorshipclaim_publication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="discipline",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="expertises",
        ),
    ]
