# Generated by Django 4.2.10 on 2024-03-14 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0147_auto_20240220_1404"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scipost", "0040_auto_20210310_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remark",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scipost.contributor"
            ),
        ),
        migrations.AlterField(
            model_name="remark",
            name="recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="submissions.eicrecommendation",
            ),
        ),
        migrations.AlterField(
            model_name="remark",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="submissions.submission",
            ),
        ),
        migrations.AlterField(
            model_name="totpdevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
