# Generated by Django 5.0.12 on 2025-03-20 13:45

from django.db import migrations, models


def toggle_is_anonymous(apps, schema_editor):
    """
    Set is_anonymous to True for all contributors with a first name == "Anonymous".
    """
    Contributor = apps.get_model("scipost", "Contributor")
    Contributor.objects.filter(user__username__startswith="anonymous").update(
        is_anonymous=True
    )
    Contributor.objects.exclude(user__username__startswith="anonymous").update(
        is_anonymous=False
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "scipost",
            "0041_alter_remark_contributor_alter_remark_recommendation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(toggle_is_anonymous, migrations.RunPython.noop),
    ]
