# Generated by Django 5.0.12 on 2025-03-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0043_rename_contributor_user_to_dbuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="vetted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contrib_vetted_by",
                to="scipost.contributor",
            ),
        ),
    ]
