# Generated by Django 5.0.12 on 2025-05-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scipost", "0044_alter_contributor_vetted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totpdevice",
            name="token",
            field=models.CharField(max_length=32),
        ),
    ]
