# Generated by Django 5.0.12 on 2025-06-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scipost", "0045_alter_totpdevice_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="anonymous_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Aggregated statistics saved prior to anonymization.",
            ),
        ),
    ]
