# Use minimal alpine image
FROM python:3.11-alpine

# Install packages
RUN apk add \
    git \
    g++ make \
    nodejs npm \
    # for geopandas
    gdal-dev geos-dev 

# Clone the repository
COPY ../ /app

# Create a non-root user named 'scipost'
RUN adduser -D scipost

# Create scipost-managed directories
RUN mkdir -p /var/log/scipost
RUN mkdir -p /data/scipost

RUN chown -R scipost:scipost /var/log/scipost
RUN chown -R scipost:scipost /data/scipost
RUN chown -R scipost:scipost /app

USER scipost

# Install python dependencies
WORKDIR /app
RUN python -m venv /app/venv
RUN source /app/venv/bin/activate && pip install --prefer-binary --no-cache-dir  -r requirements.txt
