# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 03:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20160415_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='referees_flagged',
            field=models.TextField(blank=True, null=True),
        ),
    ]
