# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20160515_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorialcommunication',
            old_name='type',
            new_name='comtype',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assigned',
        ),
        migrations.AlterField(
            model_name='submission',
            name='open_for_commenting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='open_for_reporting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned to a specialty editor (response pending)'), ('assignment_failed', 'Failed to assign Editor-in-charge; manuscript rejected'), ('EICassigned', 'Editor-in-charge assigned, manuscript under review'), ('review_closed', 'Review period closed, editorial recommendation pending'), ('EIC_has_recommended', 'Editor-in-charge has provided recommendation'), ('put_to_EC_voting', 'Undergoing voting at the Editorial College'), ('EC_vote_completed', 'Editorial College voting rounded up'), ('decided', 'Publication decision taken')], max_length=30),
        ),
    ]
