# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-27 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20160521_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeinvitation',
            name='date_last_reminded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refereeinvitation',
            name='nr_reminders',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='editorialcommunication',
            name='comtype',
            field=models.CharField(choices=[('EtoA', 'Editor-in-charge to Author'), ('EtoR', 'Editor-in-charge to Referee'), ('EtoS', 'Editor-in-charge to SciPost Editorial Administration'), ('AtoE', 'Author to Editor-in-charge'), ('RtoE', 'Referee to Editor-in-Charge'), ('StoE', 'SciPost Editorial Administration to Editor-in-charge')], max_length=4),
        ),
    ]
