# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20160610_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(blank=True, choices=[('Letter', 'Letter (broad-interest breakthrough results)'), ('Article', 'Article (in-depth reports on specialized research)'), ('Review', 'Review (candid snapshot of current research area)')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eicrecommendation',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assignment_failed', 'Failed to assign Editor-in-charge; manuscript rejected'), ('EICassigned', 'Editor-in-charge assigned, manuscript under review'), ('review_closed', 'Review period closed, editorial recommendation pending'), ('revision_requested', 'Editor-in-charge has requested revision'), ('put_to_EC_voting', 'Undergoing voting at the Editorial College'), ('EC_vote_completed', 'Editorial College voting rounded up'), ('accepted', 'Publication decision taken: accept'), ('rejected', 'Publication decision taken: reject'), ('withdrawn', 'Withdrawn by the Authors')], max_length=30),
        ),
    ]
