# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_auto_20160706_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(blank=True, choices=[('Letter', 'Letter (broad-interest breakthrough results)'), ('Article', 'Article (in-depth reports on specialized research)'), ('Review', 'Review (candid snapshot of current research in a given area)')], default=None, max_length=10, null=True),
        ),
    ]
