# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_auto_20160712_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='arxiv_identifier_w_vn_nr',
            field=models.CharField(default='0000.00000v0', max_length=15),
        ),
        migrations.AddField(
            model_name='submission',
            name='arxiv_identifier_wo_vn_nr',
            field=models.CharField(default='0000.00000', max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='arxiv_vn_nr',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='author_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_resubmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='list_of_changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned, undergoing pre-screening'), ('assignment_failed', 'Failed to assign Editor-in-charge; manuscript rejected'), ('EICassigned', 'Editor-in-charge assigned, manuscript under review'), ('review_closed', 'Review period closed, editorial recommendation pending'), ('revision_requested', 'Editor-in-charge has requested revision'), ('resubmitted', 'Has been resubmitted'), ('put_to_EC_voting', 'Undergoing voting at the Editorial College'), ('EC_vote_completed', 'Editorial College voting rounded up'), ('accepted', 'Publication decision taken: accept'), ('rejected', 'Publication decision taken: reject'), ('withdrawn', 'Withdrawn by the Authors')], max_length=30),
        ),
    ]
