# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-09 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0011_unavailabilityperiod'),
        ('submissions', '0014_auto_20160802_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='eicrecommendation',
            name='voted_abstain',
            field=models.ManyToManyField(blank=True, related_name='voted_abstain', to='scipost.Contributor'),
        ),
    ]
