# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-10 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_eicrecommendation_voted_abstain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='discipline',
            field=models.CharField(choices=[('physics', 'Physics'), ('mathematics', 'Mathematics'), ('computerscience', 'Computer Science')], default='physics', max_length=20),
        ),
    ]
