# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_auto_20160810_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='referees_suggested',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='discipline',
            field=models.CharField(choices=[('physics', 'Physics'), ('astrophysics', 'Astrophysics'), ('mathematics', 'Mathematics'), ('computerscience', 'Computer Science')], default='physics', max_length=20),
        ),
    ]
