# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 10:46
from __future__ import unicode_literals

from django.db import migrations


def rename_submission_status(apps, schema_editor):
    """Rename Submission incoming status."""
    Submission = apps.get_model('submissions', 'Submission')

    # Update Submission statuses
    Submission.objects.filter(status='unassigned_incoming').update(status='incoming')


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_auto_20180426_1023'),
    ]

    operations = [
        migrations.RunPython(rename_submission_status),
    ]
