# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-13 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_auto_20160813_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eicrecommendation',
            name='remarks_during_voting',
        ),
    ]
