# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0023_auto_20160914_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeinvitation',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
