# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0024_refereeinvitation_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='remarks_for_editors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
