# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0025_auto_20180520_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeinvitation',
            name='auto_reminders_allowed',
            field=models.NullBooleanField(default=None),
        ),
    ]
