# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0030_auto_20170313_1646'),
        ('submissions', '0030_auto_20170313_1643'),
    ]

    operations = [
    ]
