# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0031_merge_20170325_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Vetted'), (0, 'Unvetted'), (-2, 'Rejected (incorrect)'), (-1, 'Rejected (unclear)'), (-3, 'Rejected (not useful)'), (-4, 'Rejected (not academic in style)')], default=0),
        ),
    ]
