# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0032_auto_20170404_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_to_journal',
            field=models.CharField(choices=[('SciPost Physics', 'SciPost Physics'), ('SciPostPhysLecture', 'SciPost Physics Lecture Notes')], max_length=30, verbose_name='Journal to be submitted to'),
        ),
    ]
