# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0034_auto_20170407_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_to_journal',
            field=models.CharField(choices=[('SciPostPhys', 'SciPost Physics'), ('SciPostPhysLectNotes', 'SciPost Physics Lecture Notes')], max_length=30, verbose_name='Journal to be submitted to'),
        ),
    ]
