# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0038_auto_20170415_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eicrecommendation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eicrecommendations', to='submissions.Submission'),
        ),
    ]
