# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-11 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0041_auto_20170418_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateField(default=datetime.date.today, verbose_name='submission date'),
        ),
    ]
