# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0042_auto_20170511_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='latest_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
