# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-15 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0043_remove_submission_submitted_to_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Journal'),
        ),
    ]
