# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models


def do_nothing(apps, schema_editor):
    pass


def auto_fill_acceptance_dates(apps, schema_editor):
    Publication = apps.get_model('journals', 'Publication')
    for pub in Publication.objects.all():
        submission = pub.accepted_submission
        submission.acceptance_date = pub.acceptance_date
        submission.save()
    print("Auto-filled Acceptance dates for accepted Submissions")


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0046_auto_20170623_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='acceptance_date',
            field=models.DateField(blank=True, null=True, verbose_name='acceptance date'),
        ),
        migrations.RunPython(auto_fill_acceptance_dates, do_nothing),
    ]
