# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0046_auto_20170625_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_report',
            field=models.FileField(blank=True, max_length=200, upload_to='UPLOADS/REPORTS/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_nr',
            field=models.PositiveSmallIntegerField(default=0, help_text='This number is a unique number refeering to the Report nr. of the Submission'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('submission', 'report_nr')]),
        ),
    ]
