# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-21 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0047_submission_acceptance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='requested_changes',
            field=models.TextField(blank=True, verbose_name='requested changes'),
        ),
        migrations.AlterField(
            model_name='report',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='weaknesses',
            field=models.TextField(blank=True),
        ),
    ]
