# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0047_auto_20170625_1331'),
        ('submissions', '0047_submission_acceptance_date'),
    ]

    operations = [
    ]
