# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0048_merge_20170707_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pdf_refereeing_pack',
            field=models.FileField(blank=True, max_length=200, upload_to='UPLOADS/REFEREE/%Y/%m/'),
        ),
    ]
