# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-21 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0048_auto_20170721_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='formatting',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'perfect'), (5, 'excellent'), (4, 'good'), (3, 'reasonable'), (2, 'acceptable'), (1, 'below threshold'), (0, 'mediocre')], null=True, verbose_name='Quality of paper formatting'),
        ),
        migrations.AlterField(
            model_name='report',
            name='grammar',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'perfect'), (5, 'excellent'), (4, 'good'), (3, 'reasonable'), (2, 'acceptable'), (1, 'below threshold'), (0, 'mediocre')], null=True, verbose_name='Quality of English grammar'),
        ),
        migrations.AlterField(
            model_name='report',
            name='qualification',
            field=models.PositiveSmallIntegerField(choices=[(4, 'expert in this subject'), (3, 'very knowledgeable in this subject'), (2, 'knowledgeable in this subject'), (1, 'generally qualified'), (0, 'not qualified')], verbose_name='Qualification to referee this: I am'),
        ),
        migrations.AlterField(
            model_name='report',
            name='remarks_for_editors',
            field=models.TextField(blank=True, verbose_name='optional remarks for the Editors only'),
        ),
    ]
