# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-07 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0039_auto_20181011_0746'),
        ('submissions', '0049_auto_20181204_2040'),
    ]

    operations = [
    ]
