# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0049_submission_pdf_refereeing_pack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['report_nr']},
        ),
        migrations.AddField(
            model_name='report',
            name='doi_label',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
