# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-18 21:01
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0050_merge_20181207_1008'),
    ]

    operations = [
        # TrigramExtension(),
    ]
