# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-21 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0050_auto_20170707_2126'),
        ('submissions', '0048_auto_20170721_0931'),
    ]

    operations = [
    ]
