# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-21 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0050_auto_20170721_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='formatting',
            field=models.SmallIntegerField(blank=True, choices=[(None, '-'), (6, 'perfect'), (5, 'excellent'), (4, 'good'), (3, 'reasonable'), (2, 'acceptable'), (1, 'below threshold'), (0, 'mediocre')], null=True, verbose_name='Quality of paper formatting'),
        ),
        migrations.AlterField(
            model_name='report',
            name='grammar',
            field=models.SmallIntegerField(blank=True, choices=[(None, '-'), (6, 'perfect'), (5, 'excellent'), (4, 'good'), (3, 'reasonable'), (2, 'acceptable'), (1, 'below threshold'), (0, 'mediocre')], null=True, verbose_name='Quality of English grammar'),
        ),
    ]
