# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-03 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0051_auto_20190126_2058'),
        ('submissions', '0051_auto_20181218_2201'),
    ]

    operations = [
    ]
