# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-03 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0052_merge_20190303_1241'),
        ('submissions', '0052_merge_20190209_1124'),
    ]

    operations = [
    ]
