# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0053_merge_20190303_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='update_search_index',
            field=models.BooleanField(default=True),
        ),
    ]
