# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0051_merge_20170721_0934'),
        ('submissions', '0054_auto_20170721_1148'),
    ]

    operations = [
    ]
