# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0055_auto_20170724_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionevent',
            old_name='blub',
            new_name='text',
        ),
    ]
