# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0056_auto_20170724_1818'),
        ('submissions', '0051_merge_20170721_0934'),
    ]

    operations = [
    ]
