# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-24 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0057_merge_20170724_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date_submitted']},
        ),
    ]
