# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0058_auto_20170724_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionevent',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='eicrecommendation',
            name='remarks_for_editorial_college',
            field=models.TextField(blank=True, default='', verbose_name='optional remarks for the Editorial College'),
            preserve_default=False,
        ),
    ]
