# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0055_merge_20170724_1958'),
        ('submissions', '0059_auto_20170725_2048'),
    ]

    operations = [
    ]
