# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-27 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0061_auto_20170727_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date_submitted'], 'permissions': (('can_vet_submitted_reports', 'Can vet submitted Reports'),)},
        ),
    ]
