# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scipost.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0062_auto_20170727_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='iThenticateReport',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_activity', scipost.db.fields.AutoDateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('uploaded_time', models.DateTimeField(blank=True, null=True)),
                ('processed_time', models.DateTimeField(blank=True, null=True)),
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('percent_match', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='plagiarism_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_submission', to='submissions.iThenticateReport'),
        ),
    ]
