# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0063_auto_20170812_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ithenticatereport',
            options={'verbose_name': 'iThenticate Report', 'verbose_name_plural': 'iThenticate Reports'},
        ),
    ]
