# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0064_auto_20170815_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorialassignment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='editorialassignment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_assignments', to='submissions.Submission'),
        ),
        migrations.AlterField(
            model_name='editorialassignment',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_assignments', to='scipost.Contributor'),
        ),
    ]
