# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0065_auto_20170829_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='ithenticatereport',
            name='part_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
