# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0069_report_doideposit_needs_updating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeinvitation',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_invitations', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='author_comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='authors_claims',
            field=models.ManyToManyField(blank=True, related_name='claimed_submissions', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='authors_false_claims',
            field=models.ManyToManyField(blank=True, related_name='false_claimed_submissions', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='list_of_changes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='referees_flagged',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='referees_suggested',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='remarks_for_editors',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_submissions', to='scipost.Contributor'),
        ),
    ]
