# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0069_report_doideposit_needs_updating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='author_comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
