# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0070_auto_20170925_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeinvitation',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_invitations', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_submissions', to='scipost.Contributor'),
        ),
    ]
