# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0071_auto_20170928_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='list_of_changes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
