# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0072_auto_20170928_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='authors_claims',
            field=models.ManyToManyField(blank=True, related_name='claimed_submissions', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='authors_false_claims',
            field=models.ManyToManyField(blank=True, related_name='false_claimed_submissions', to='scipost.Contributor'),
        ),
    ]
