# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0073_auto_20170928_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='referees_flagged',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
