# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('submissions', '0076_auto_20170928_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pool',
            field=models.ManyToManyField(blank=True, related_name='pool', to='colleges.Fellowship'),
        ),
    ]
