# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('proceedings', '0001_initial'),
        ('submissions', '0076_auto_20170928_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='fellows',
            field=models.ManyToManyField(blank=True, related_name='pool', to='colleges.Fellowship'),
        ),
        migrations.AddField(
            model_name='submission',
            name='proceedings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='proceedings.Proceedings'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_to_journal',
            field=models.CharField(choices=[('SciPostPhys', 'SciPost Physics'), ('SciPostPhysLectNotes', 'SciPost Physics Lecture Notes'), ('SciPostPhysProc', 'SciPost Proceedings')], max_length=30, verbose_name='Journal to be submitted to'),
        ),
    ]
