# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 07:45
from __future__ import unicode_literals

from django.db import migrations


def fill_editorial_college(apps, schema_editor):
    Fellowship = apps.get_model('colleges', 'EditorialCollegeFellowship')
    Submission = apps.get_model('submissions', 'Submission')
    fellows = Fellowship.objects.all()

    for submission in Submission.objects.all():
        for fellow in fellows:
            cont = fellow.contributor
            if cont not in submission.authors.all() and cont not in submission.authors_claims.all() and (cont.user.last_name not in submission.author_list or cont in submission.authors_false_claims.all()):
                submission.pool.add(fellow)


def no_going_back(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0077_submission_pool'),
        ('colleges', '0002_auto_20171014_0938'),
    ]

    operations = [
        migrations.RunPython(fill_editorial_college, no_going_back),
    ]
