# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0078_auto_20171020_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
    ]
