# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0080_submission_proceedings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='proceedings',
            new_name='proceeding',
        ),
    ]
