# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20171020_0931'),
        ('submissions', '0080_auto_20171101_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='voting_fellows',
            field=models.ManyToManyField(blank=True, related_name='voting_pool', to='colleges.Fellowship'),
        ),
    ]
