# Generated by Django 2.2.11 on 2020-06-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0081_auto_20191026_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorialdecision',
            options={'ordering': ['-submission__submission_date', '-version'], 'verbose_name': 'Editorial Decision', 'verbose_name_plural': 'Editorial Decisions'},
        ),
    ]
