# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0082_auto_20171019_1942'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='submission',
        #     old_name='proceeding',
        #     new_name='proceedings',
        # ),
    ]
