# Generated by Django 2.2.16 on 2020-09-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0096_auto_20200926_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='secondary_areas',
        ),
    ]
