# Generated by Django 2.2.16 on 2020-09-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0099_populate_preprint_server_acad_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprintserver',
            name='disciplines',
        ),
    ]
