# Generated by Django 2.2.16 on 2020-10-23 06:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimail', '0024_auto_20201017_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='composedmessage',
            name='headers_added',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
