# Generated by Django 2.2.16 on 2020-10-24 15:51

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apimail', '0025_composedmessage_headers_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=512, unique=True)),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='AddressValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('datestamp', models.DateField(default=datetime.date.today)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='apimail.ValidatedAddress')),
            ],
            options={
                'ordering': ['address__address', '-datestamp'],
            },
        ),
    ]
