# Generated by Django 2.1.8 on 2019-11-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
