# Generated by Django 2.1.8 on 2019-11-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0005_auto_20191130_1156"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="last_udpated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
