# Generated by Django 3.2.18 on 2023-10-09 16:12

import comments.behaviors
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0007_auto_20210310_2026"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"ordering": ["-job_opening__announced", "last_name"]},
        ),
        migrations.RenameField(
            model_name="jobapplication",
            old_name="jobopening",
            new_name="job_opening",
        ),
        migrations.RenameField(
            model_name="jobapplication",
            old_name="last_udpated",
            new_name="last_updated",
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cv",
            field=models.FileField(
                help_text="Your curriculum vitae, including details of training and skills pertinent to this particular job (pdf file)",
                upload_to="uploads/job_applications/%Y/%m/",
                validators=[
                    comments.behaviors.validate_file_extension,
                    comments.behaviors.validate_max_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="motivation",
            field=models.FileField(
                help_text="Please describe your motivations for applying, and your qualifications for this particular job (pdf file)",
                upload_to="uploads/job_applications/%Y/%m/",
                validators=[
                    comments.behaviors.validate_file_extension,
                    comments.behaviors.validate_max_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job_opening",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to="careers.jobopening",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
