# Generated by Django 5.2.5 on 2026-01-16 15:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0008_auto_20231009_1812"),
        ("scipost", "0045_alter_totpdevice_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkContract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Salary"),
                            ("hourly", "Hourly Wage"),
                        ],
                        default="hourly",
                        max_length=16,
                    ),
                ),
                (
                    "pay_rate",
                    models.FloatField(
                        default=20.0,
                        help_text="Monthly salary or hourly wage, depending on salary type.",
                    ),
                ),
                (
                    "work_hours_week",
                    models.DurationField(
                        default=datetime.timedelta(days=1, seconds=50400),
                        help_text="Number of work hours per week (e.g., 38 for full-time).",
                    ),
                ),
                (
                    "days_off",
                    models.IntegerField(
                        default=31, help_text="Number of paid days off per year."
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scipost.contributor",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "default_related_name": "work_contracts",
            },
        ),
    ]
