# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-17 09:51
from __future__ import unicode_literals

from django.db import migrations


def set_statuses(apps, schema_editor):
    MailLog = apps.get_model('mails', 'MailLog')
    MailLog.objects.filter(processed=True).update(status='sent')


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_auto_20181217_1050'),
    ]

    operations = [
        migrations.RunPython(set_statuses, reverse_code=migrations.RunPython.noop),
    ]
