# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0002_auto_20180217_1449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationinvitation",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
