# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invitations", "0003_auto_20180217_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationinvitation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
