# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0004_registrationinvitation_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationinvitation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
