# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0005_auto_20180217_1554"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationinvitation",
            old_name="number_of_reminders",
            new_name="times_sent",
        ),
    ]
