# Generated by Django 4.2.10 on 2024-03-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0015_auto_20210310_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citationnotification",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invitations.registrationinvitation",
            ),
        ),
    ]
