# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-15 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprints', '0008_auto_20180819_1343'),
        ('preprints', '0008_auto_20180913_2112'),
    ]

    operations = [
    ]
