# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-07 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprints', '0009_merge_20180915_1337'),
        ('preprints', '0009_auto_20181123_1000'),
    ]

    operations = [
    ]
