# Generated by Django 2.2.11 on 2020-07-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprints', '0011_remove_preprint_scipost_preprint_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprint',
            name='identifier_wo_vn_nr',
        ),
        migrations.RemoveField(
            model_name='preprint',
            name='vn_nr',
        ),
    ]
