# Generated by Django 4.2.15 on 2025-01-09 16:11

from itertools import combinations
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from profiles.models import Profile
from scipost.models import Contributor


def migrate_nonduplicate_profiles(apps, schema_editor):
    ProfileNonDuplicates = apps.get_model("profiles", "ProfileNonDuplicates")
    NonDuplicate = apps.get_model("common", "NonDuplicate")

    profile_content_type = ContentType.objects.get_for_model(Profile)
    system = Contributor.objects.get(user__username="system")

    non_duplicates = []
    for profile_nonduplicate in ProfileNonDuplicates.objects.all():
        for profile_a, profile_b in combinations(
            profile_nonduplicate.profiles.all(), 2
        ):
            non_duplicates.append(
                NonDuplicate(
                    content_type_id=profile_content_type.id,
                    contributor_id=system.id,
                    description=profile_nonduplicate.get_reason_display(),
                    object_a_id=profile_a.id,
                    object_b_id=profile_b.id,
                )
            )

    NonDuplicate.objects.bulk_create(non_duplicates)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            migrate_nonduplicate_profiles,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
