# Generated by Django 5.0.12 on 2025-03-04 16:49

from django.db import migrations, models
from django.db.models import F


def enforce_object_id_order(apps, schema_editor):
    Nonduplicate = apps.get_model("common", "Nonduplicate")

    Nonduplicate.objects.filter(object_a_id__gt=F("object_b_id")).update(
        object_a_id=F("object_b_id"), object_b_id=F("object_a_id")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_migrate_nonduplicate_profiles"),
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "scipost",
            "0041_alter_remark_contributor_alter_remark_recommendation_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nonduplicate",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="nonduplicate",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_a_id", "object_b_id"),
                name="unique_non_duplicate",
                violation_error_message="This non-duplicate declaration already exists",
            ),
        ),
        migrations.RunPython(
            enforce_object_id_order, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="nonduplicate",
            constraint=models.CheckConstraint(
                check=models.Q(("object_a_id__lt", models.F("object_b_id"))),
                name="object_a_lt_object_b",
                violation_error_message="To avoid duplicate declarations, object_a_id must be less than object_b_id",
            ),
        ),
    ]
