# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20190312_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='parent_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_queues', to='helpdesk.Queue'),
        ),
    ]
