# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0005_followup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="action",
            field=models.CharField(
                choices=[
                    ("assignment", "Assignment"),
                    ("reassignment", "Reassignment"),
                    ("pickup", "Pickup by handler"),
                    ("respondedtouser", "Response sent to user"),
                    ("userresonponded", "User responded"),
                    ("markresolved", "Marked as resolved"),
                    ("markcloseed", "Mark as closeed"),
                ],
                max_length=32,
            ),
        ),
    ]
