# Generated by Django 3.2.18 on 2023-10-26 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scipost', '0040_auto_20210310_2026'),
        ('ethics', '0003_auto_20230119_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concerning_object_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('raised_on', models.DateField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('concerning_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags_raised', to='scipost.contributor')),
            ],
        ),
    ]
