# Generated by Django 5.0.12 on 2025-08-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ethics", "0004_redflag"),
        ("scipost", "0045_alter_totpdevice_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenAIDisclosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("was_used", models.BooleanField(blank=True, default=None, null=True)),
                ("use_details", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scipost.contributor",
                    ),
                ),
            ],
            options={
                "default_related_name": "gen_ai_disclosures",
            },
        ),
        migrations.AddConstraint(
            model_name="genaidisclosure",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"),
                name="unique_gen_ai_disclosure_per_object",
                violation_error_message="GenAI disclosure already exists for this object.",
            ),
        ),
    ]
