# Generated by Django 5.2.5 on 2025-09-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethics", "0008_coauthorships_auto_add_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="coauthorship",
            name="competing_interest",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coauthorship",
                to="ethics.competinginterest",
            ),
        ),
    ]
