# Generated by Django 5.2.5 on 2025-09-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethics", "0009_coauthorship_competing_interest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coauthorship",
            options={"ordering": ["-status", "-work__date_published", "work__title"]},
        ),
        migrations.AlterField(
            model_name="coauthoredwork",
            name="date_fetched",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="coauthorship",
            name="_cf_coauthor_idx_in_authors_str",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coauthorship",
            name="_cf_profile_idx_in_authors_str",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
