# Generated by Django 5.2.5 on 2025-10-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethics", "0010_alter_coauthorship_options_and_more"),
        ("journals", "0140_alter_issue_doi_label_alter_journal_doi_label_and_more"),
        ("profiles", "0050_create_nonduplicatemarks_from_profiles"),
        ("scipost", "0045_alter_totpdevice_token"),
        (
            "submissions",
            "0171_rename_needs_conflicts_update_submission_needs_coauthorships_update",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompetingInterest",
            new_name="ConflictOfInterest",
        ),
        migrations.RenameField(
            model_name="coauthorship",
            old_name="competing_interest",
            new_name="conflict_of_interest",
        ),
        migrations.AlterField(
            model_name="conflictofinterest",
            name="affected_publications",
            field=models.ManyToManyField(
                blank=True,
                related_name="conflicts_of_interest",
                to="journals.publication",
            ),
        ),
        migrations.AlterField(
            model_name="conflictofinterest",
            name="affected_submissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="conflicts_of_interest",
                to="submissions.submission",
            ),
        ),
        migrations.AlterField(
            model_name="conflictofinterest",
            name="declared_by",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="declared_conflicts_of_interest",
                to="scipost.contributor",
            ),
        ),
        migrations.AlterField(
            model_name="conflictofinterest",
            name="profile",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="conflicts_of_interest",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="conflictofinterest",
            name="related_profile",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="related_conflicts_of_interest",
                to="profiles.profile",
            ),
        ),
    ]
