# Generated by Django 5.2.5 on 2025-10-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ethics", "0011_rename_competing_interest_to_conflict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conflictofinterest",
            name="affected_publications",
        ),
        migrations.RemoveField(
            model_name="conflictofinterest",
            name="affected_submissions",
        ),
    ]
