# Generated by Django 5.2.5 on 2025-10-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethics", "0012_remove_conflictofinterest_affected_publications_and_more"),
        (
            "submissions",
            "0171_rename_needs_conflicts_update_submission_needs_coauthorships_update",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conflictofinterest",
            name="exempted_submissions",
            field=models.ManyToManyField(
                blank=True, related_name="exempted_cois", to="submissions.submission"
            ),
        ),
    ]
