# Generated by Django 5.2.5 on 2025-11-03 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


def exempted_submission_to_thread(apps, schema_editor):
    ConflictOfInterest = apps.get_model("ethics", "ConflictOfInterest")

    for coi in ConflictOfInterest.objects.filter(exempted_submissions__isnull=False):
        coi.exempted_submission_threads = list(
            set(submission.thread_hash for submission in coi.exempted_submissions.all())
        )
        coi.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ethics", "0013_conflictofinterest_exempted_submissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="conflictofinterest",
            name="exempted_submission_threads",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(max_length=64),
                blank=True,
                default=list,
                help_text="List of submission thread hashes for which this conflict of interest is exempted.",
                size=None,
            ),
        ),
        migrations.RunPython(exempted_submission_to_thread, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="conflictofinterest",
            name="exempted_submissions",
        ),
    ]
