# Generated by Django 5.2.5 on 2026-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethics", "0014_remove_conflictofinterest_exempted_submissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coauthoredwork",
            name="work_type",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
