# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 11:24
from __future__ import unicode_literals

from django.db import migrations


# def populate_organization_from_partners_orgs(apps, schema_editor):
#     Organization = apps.get_model('organizations', 'Organization')
#     PartnersOrganization = apps.get_model('partners', 'Organization')

#     # First of all, copy each exising instace, omitting the parent and superseded_by fields
#     # (since these are self-referencing ForeignKeys).
#     for oldorg in PartnersOrganization.objects.all():
#         org = Organization(
#             orgtype=oldorg.orgtype,
#             status=oldorg.status,
#             name=oldorg.name,
#             name_original=oldorg.name_original,
#             acronym=oldorg.acronym,
#             country=oldorg.country,
#             address=oldorg.address,
#             logo=oldorg.logo,
#             css_class=oldorg.css_class,
#             grid_json=oldorg.grid_json,
#             crossref_json=oldorg.crossref_json,
#             cf_nr_associated_publications=oldorg.cf_nr_associated_publications)
#         org.save()

#     # Now copy the ForeignKeys to self: first, parent:
#     for oldorg in PartnersOrganization.objects.all():
#         if oldorg.parent:
#             org = Organization.objects.get(name=oldorg.name)
#             parent = Organization.objects.get(name=oldorg.parent.name)
#             org.parent = parent
#             org.save()
#     # then, superseded_by:
#     for oldorg in PartnersOrganization.objects.all():
#         if oldorg.superseded_by:
#             org = Organization.objects.get(name=oldorg.name)
#             superseded_by = Organization.objects.get(name=oldorg.superseded_by.name)
#             org.superseded_by = superseded_by
#             org.save()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        # migrations.RunPython(populate_organization_from_partners_orgs,
        #                      reverse_code=migrations.RunPython.noop),
    ]
