# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-19 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0003_contact_contactperson_contactrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("requested", "Requested (from online form)"),
                            ("comment", "Comment added"),
                            ("email_sent", "Email sent"),
                            ("negotiating", "Initiated negotiation"),
                            ("marked_as_uninterested", "Marked as uninterested"),
                            ("promoted", "Promoted to Sponsor"),
                            ("status_updated", "Status updated"),
                        ],
                        max_length=64,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("noted_on", models.DateTimeField(auto_now_add=True)),
                (
                    "noted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.Organization",
                    ),
                ),
            ],
        ),
    ]
