# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-19 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationevent',
            name='noted_on',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
