# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-21 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_auto_20190219_2058"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["country", "name"],
                "permissions": (
                    ("can_view_org_contacts", "Can view this Organization's Contacts"),
                ),
            },
        ),
    ]
