# Generated by Django 3.2.13 on 2022-06-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_auto_20220314_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ror_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
