# Generated by Django 3.2.18 on 2023-11-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_auto_20220314_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='grid_json',
            new_name='ror_json',
        ),
    ]
