# Generated by Django 4.2.15 on 2024-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0021_enable_unaccent"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactperson",
            name="date_deprecated",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactperson",
            name="status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("active", "Active"),
                    ("deprecated", "Deprecated"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
    ]
