# Generated by Django 4.2.15 on 2024-10-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0023_alter_contactperson_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactperson",
            name="info_source",
            field=models.TextField(blank=True, verbose_name="Information source"),
        ),
    ]
