# Generated by Django 5.2.5 on 2026-03-09 10:28

import common.utils.lookups
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0024_contactperson_info_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="name_normalized",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Lower(
                    common.utils.lookups.ImmutableUnaccent("name")
                ),
                output_field=models.CharField(max_length=256),
            ),
        ),
    ]
