# Generated by Django 5.2.5 on 2026-06-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0025_organization_name_normalized_organization_ror_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="crossref_json",
        ),
    ]
