# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0026_submission_needs_conflicts_update'),
        ('conflicts', '0004_conflictofinterest_related_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='conflictofinterest',
            name='conflict_title',
        ),
        migrations.RemoveField(
            model_name='conflictofinterest',
            name='conflict_url',
        ),
        migrations.RemoveField(
            model_name='conflictofinterest',
            name='related_submissions',
        ),
        migrations.AddField(
            model_name='conflictgroup',
            name='conflicts',
            field=models.ManyToManyField(blank=True, to='conflicts.ConflictOfInterest'),
        ),
        migrations.AddField(
            model_name='conflictgroup',
            name='related_submissions',
            field=models.ManyToManyField(blank=True, related_name='conflicts', to='submissions.Submission'),
        ),
    ]
