# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_auto_20181007_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsidy",
            name="description",
            field=models.TextField(),
        ),
    ]
