# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-08 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0004_auto_20181007_2016"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subsidy",
            name="duration",
        ),
        migrations.AddField(
            model_name="subsidy",
            name="date_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
