# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0007_auto_20181011_2146"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsidy",
            name="amount_publicly_shown",
            field=models.BooleanField(default=True),
        ),
    ]
