# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-25 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import finances.models
import scipost.storage


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0014_subsidy_renewable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsidyattachment",
            name="attachment",
            field=models.FileField(
                storage=scipost.storage.SecureFileStorage(),
                upload_to=finances.models.subsidy_attachment_path,
            ),
        ),
    ]
