# Generated by Django 3.2.5 on 2021-07-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0016_auto_20200901_0631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsidy",
            name="renewable",
            field=models.BooleanField(null=True),
        ),
    ]
