# Generated by Django 3.2.17 on 2023-02-15 13:49

from django.db import migrations


def set_subsidy_attachment_visibility(apps, schema_editor):
    SubsidyAttachment = apps.get_model("finances.SubsidyAttachment")

    SubsidyAttachment.objects.filter(publicly_visible=True).update(
        visibility="public",
    )
    SubsidyAttachment.objects.filter(publicly_visible=False).update(
        visibility="internal",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_auto_20230215_1449'),
    ]

    operations = [
        migrations.RunPython(
            set_subsidy_attachment_visibility, reverse_code=migrations.RunPython.noop
        ),
    ]
