# Generated by Django 3.2.17 on 2023-02-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0021_subsidyattachment_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidyattachment',
            name='publicly_visible',
        ),
    ]
