# Generated by Django 3.2.17 on 2023-02-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0022_remove_subsidyattachment_publicly_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsidy",
            name="paid_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
