# Generated by Django 3.2.17 on 2023-02-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0024_auto_20230215_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsidy',
            options={'ordering': ['-date_from'], 'verbose_name_plural': 'subsidies'},
        ),
        migrations.RenameField(
            model_name='subsidy',
            old_name='date',
            new_name='date_from',
        ),
    ]
