# Generated by Django 3.2.17 on 2023-02-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0025_auto_20230215_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='in &euro;')),
                ('date_scheduled', models.DateField()),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_for', to='finances.subsidyattachment')),
                ('proof_of_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_payment_for', to='finances.subsidyattachment')),
                ('subsidy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finances.subsidy')),
            ],
        ),
    ]
