# Generated by Django 3.2.17 on 2023-02-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0026_subsidypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidyattachment',
            name='name',
        ),
    ]
