# Generated by Django 3.2.18 on 2023-11-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0027_remove_subsidyattachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='status',
            field=models.CharField(choices=[('promised', 'Promised'), ('invoiced', 'Invoiced'), ('received', 'Received'), ('withdrawn', 'Withdrawn'), ('uptodate', 'Up to date')], max_length=32),
        ),
    ]
