# Generated by Django 3.2.18 on 2024-03-12 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0029_subsidyattachment_git_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidypayment',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_for', to='finances.subsidyattachment'),
        ),
        migrations.AlterField(
            model_name='subsidypayment',
            name='proof_of_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_of_payment_for', to='finances.subsidyattachment'),
        ),
    ]
