# Generated by Django 3.2.18 on 2024-03-14 15:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0128_populate_submission_object_types'),
        ('organizations', '0021_enable_unaccent'),
        ('finances', '0031_alter_subsidyattachment_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubFrac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pubfracs', to='organizations.organization')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubfracs', to='journals.publication')),
            ],
            options={
                'unique_together': {('organization', 'publication')},
            },
        ),
    ]
