# Generated by Django 4.2.10 on 2024-03-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0034_alter_worklog_content_type_alter_worklog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="pubfrac",
            name="cf_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
