# Generated by Django 4.2.10 on 2024-03-15 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0036_populate_pubfrac_cf_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="PubFracCompensation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "pubfrac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pubfracs",
                        to="finances.pubfrac",
                    ),
                ),
                (
                    "subsidy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pubfrac_compensations",
                        to="finances.subsidy",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PubFrac Compensations",
            },
        ),
        migrations.AddConstraint(
            model_name="pubfraccompensation",
            constraint=models.UniqueConstraint(
                fields=("subsidy", "pubfrac"), name="unique_subsidy_pubfrac"
            ),
        ),
    ]
