# Generated by Django 4.2.10 on 2024-03-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0038_alter_pubfrac_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pubfraccompensation",
            name="pubfrac",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pubfrac_compensations",
                to="finances.pubfrac",
            ),
        ),
    ]
