# Generated by Django 4.2.10 on 2024-03-16 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0130_remove_publication_pubfractions_confirmed_by_authors"),
        ("finances", "0039_alter_pubfraccompensation_pubfrac"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pubfraccompensation",
            options={
                "verbose_name": "PubFrac compensation",
                "verbose_name_plural": "PubFrac compensations",
            },
        ),
        migrations.CreateModel(
            name="PublicationExpenditureCoverage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pex_coverages",
                        to="journals.publication",
                    ),
                ),
                (
                    "subsidy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pex_coverages",
                        to="finances.subsidy",
                    ),
                ),
            ],
            options={
                "verbose_name": "PEX coverage",
                "verbose_name_plural": "PEX coverages",
            },
        ),
        migrations.AddConstraint(
            model_name="publicationexpenditurecoverage",
            constraint=models.UniqueConstraint(
                fields=("subsidy", "publication"), name="unique_subsidy_publication"
            ),
        ),
    ]
