# Generated by Django 4.2.10 on 2024-03-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0040_alter_pubfraccompensation_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicationexpenditurecoverage",
            name="publication",
        ),
        migrations.RemoveField(
            model_name="publicationexpenditurecoverage",
            name="subsidy",
        ),
        migrations.AddField(
            model_name="pubfrac",
            name="compensated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compensated_pubfracs",
                to="finances.subsidy",
            ),
        ),
        migrations.DeleteModel(
            name="PubFracCompensation",
        ),
        migrations.DeleteModel(
            name="PublicationExpenditureCoverage",
        ),
    ]
