# Generated by Django 4.2.10 on 2024-03-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0042_subsidy_algorithm_subsidy_algorithm_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pubfrac",
            name="cf_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=16, null=True
            ),
        ),
    ]
