# Generated by Django 4.2.10 on 2024-06-26 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0044_remove_subsidy_algorithm_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subsidypayment",
            options={"ordering": ["date_scheduled", "reference", "amount"]},
        ),
    ]
