# Generated by Django 4.2.15 on 2024-12-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0024_contactperson_info_source"),
        ("finances", "0046_account_transaction_futureperiodictransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsidyCollective",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "default_related_name": "collectives",
                "verbose_name_plural": "subsidy collectives",
                "ordering": ["coordinator__name"],
            },
        ),
        migrations.AddField(
            model_name="subsidy",
            name="collective",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subsidies",
                to="finances.subsidycollective",
            ),
        ),
    ]
