# Generated by Django 4.2.15 on 2024-11-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0047_subsidycollective"),
        ("funders", "0016_individualbudget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsidy",
            name="subsidy_type",
            field=models.CharField(
                choices=[
                    ("sponsorshipagreement", "Sponsorship Agreement"),
                    ("incidentalgrant", "Incidental Grant"),
                    ("developmentgrant", "Development Grant"),
                    ("collaborationagreement", "Collaboration Agreement"),
                    ("coordinationsupportaction", "Coordination and Support Action"),
                    ("donation", "Donation"),
                    ("individualbudget", "Individual Budget"),
                ],
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="subsidy",
            name="individual_budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subsidies_funded",
                to="funders.individualbudget",
            ),
        ),
    ]
