# Generated by Django 5.0.12 on 2025-05-29 10:38

import finances.utils.compensations
import scipost.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0048_subsidy_individual_budget_alter_subsidy_subsidy_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subsidy",
            options={
                "get_latest_by": "date_until",
                "ordering": ["-date_from"],
                "verbose_name_plural": "subsidies",
            },
        ),
        migrations.AddField(
            model_name="subsidy",
            name="compensation_strategies_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="subsidy",
            name="compensation_strategies_keys",
            field=scipost.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("self", "Self"),
                        ("parent", "Parent"),
                        ("children", "Children"),
                        ("siblings", "Siblings"),
                        ("ids", "IDs"),
                        ("countries", "Countries"),
                        ("funders", "Funders"),
                        ("specialties", "Specialties"),
                        ("any", "Any"),
                        ("none", "None"),
                    ],
                    max_length=32,
                ),
                default=finances.utils.compensations.CompensationStrategy.get_default_strategies_keys_list,
                size=None,
            ),
        ),
    ]
