# Generated by Django 5.2.5 on 2026-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0049_alter_subsidy_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="log_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("time_off", "Time off"),
                    ("production_proofs_produced", "Proofs have been produced"),
                    (
                        "production_proofs_checked",
                        "Proofs have been checked by Supervisor",
                    ),
                    ("production_corrections_implemented", "Corrections implemented"),
                    ("production_paper_published", "Paper has been published"),
                    ("maintenance_metadata_updated", "Metadata has been updated"),
                    (
                        "production_cited_people_notified",
                        "Cited people have been notified/invited to SciPost",
                    ),
                ],
                max_length=128,
            ),
        ),
    ]
