# Generated by Django 5.2.5 on 2026-03-04 14:02

import finances.utils.compensations
import scipost.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0050_update_worklog_logtype_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsidy",
            name="compensation_strategies_keys",
            field=scipost.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("self", "Self"),
                        ("children", "Children"),
                        ("parent", "Parent"),
                        ("siblings", "Siblings"),
                        ("ids", "IDs"),
                        ("countries", "Countries"),
                        ("funders", "Funders"),
                        ("specialties", "Specialties"),
                        ("any", "Any"),
                        ("none", "None"),
                    ],
                    max_length=32,
                ),
                default=finances.utils.compensations.CompensationStrategy.get_default_strategies_keys_list,
                size=None,
            ),
        ),
    ]
