# Generated by Django 5.2.5 on 2026-03-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0051_update_compensation_strategies"),
        ("organizations", "0024_contactperson_info_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsidy",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsidies",
                to="organizations.organization",
            ),
        ),
    ]
