# Generated by Django 2.2.16 on 2021-05-09 11:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0004_auto_20210508_2012"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affiliatepublication",
            options={"ordering": ["-publication_date"]},
        ),
        migrations.AddField(
            model_name="affiliatepublication",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="affiliatepublication",
            name="_metadata_crossref",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
    ]
