# Generated by Django 3.2.5 on 2021-07-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0006_auto_20210715_1244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliatepublication",
            name="_metadata_crossref",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
