# Generated by Django 3.2.12 on 2022-02-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0007_alter_affiliatepublication__metadata_crossref"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatejournal",
            name="homepage",
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
