# Generated by Django 3.2.12 on 2022-02-26 19:37

import affiliates.models.journal
import affiliates.models.subsidy
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_auto_20220223_0737'),
        ('affiliates', '0008_affiliatejournal_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatejournal',
            name='cost_info',
            field=models.JSONField(default=affiliates.models.journal.cost_default_value),
        ),
        migrations.CreateModel(
            name='AffiliateJournalYearSubsidy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.PositiveIntegerField(help_text='in &euro; (rounded)')),
                ('year', models.PositiveSmallIntegerField(default=affiliates.models.subsidy.get_current_year)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliates.affiliatejournal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'year_subsidies',
                'ordering': ['journal', '-year', 'organization'],
            },
        ),
    ]
