# Generated by Django 3.2.12 on 2022-03-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0009_auto_20220226_2037"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatejournal",
            name="logo",
            field=models.ImageField(blank=True, upload_to="affiliates/journals/logos/"),
        ),
    ]
