# Generated by Django 3.2.12 on 2022-03-04 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0007_Branch_Field_Specialty'),
        ('affiliates', '0010_affiliatejournal_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatejournal',
            name='acad_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ontology.academicfield'),
        ),
        migrations.AddField(
            model_name='affiliatejournal',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='ontology.Specialty'),
        ),
    ]
