# Generated by Django 3.2.12 on 2022-03-04 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0011_auto_20220304_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatejournal',
            name='logo_svg',
            field=models.FileField(blank=True, upload_to='affiliates/journals/logos/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
