# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='count_crossref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='count_metacore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
