# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 07:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacore', '0002_auto_20180417_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='count_running',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='ISSN_digital',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}-[0-9]{3}[0-9X]$')]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='ISSN_print',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}-[0-9]{3}[0-9X]$')]),
        ),
    ]
