# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-12 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacore', '0004_auto_20180508_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='last_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
