# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacore', '0005_journal_last_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='last_task_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
