# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-28 18:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacore', '0006_auto_20180612_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='ISSN_print',
            field=models.CharField(blank=True, default='', max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{4}-[0-9]{3}[0-9X]$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='last_cursor',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='last_errors',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='last_task_id',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
    ]
