# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('type', models.CharField(choices=[('university', 'University')], default='university', max_length=16)),
            ],
        ),
    ]
