# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 19:22
from __future__ import unicode_literals

from django.db import migrations


def fill_institutions(apps, schema_editor):
    Contributor = apps.get_model('scipost', 'Contributor')
    Institution = apps.get_model('affiliations', 'Institution')
    for contributor in Contributor.objects.all():
        affiliation, __ = Institution.objects.get_or_create(
            name=contributor.affiliation, country=contributor.country_of_employment)
        contributor._affiliation = affiliation
        contributor.save()


def return_none(*args, **kwargs):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0002_affiliation_acronym'),
        ('scipost', '0066_contributor__affiliation')
    ]

    operations = [
        migrations.RunPython(fill_institutions, return_none),
    ]
