# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-05 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0003_institution_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
