# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0003_auto_20171101_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ['country']},
        ),
    ]
