# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0007_auto_20171102_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institute',
            new_name='Institution',
        ),
    ]
