# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 16:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                ("body", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                (
                    "to_recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "bcc_recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("from_name", models.CharField(blank=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
