# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maillog",
            old_name="from_name",
            new_name="from_email",
        ),
    ]
