# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20180313_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maillog',
            name='latest_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
