# Generated by Django 3.2.5 on 2021-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0006_auto_20190220_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maillogrelation",
            name="value",
            field=models.TextField(blank=True),
        ),
    ]
