# Generated by Django 4.2.10 on 2024-03-26 16:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0007_alter_maillogrelation_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="maillog",
            name="cc_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
