# Generated by Django 5.2.5 on 2025-10-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mails", "0010_mailaddressdomain"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maillog",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="maillog",
            name="message_id",
            field=models.CharField(
                blank=True, help_text="The Message-ID header", max_length=254, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="maillog",
            constraint=models.UniqueConstraint(
                fields=("message_id",),
                name="unique_message_id",
                nulls_distinct=True,
                violation_error_message="Message-ID header must be unique",
            ),
        ),
    ]
