# Generated by Django 5.2.5 on 2026-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0011_add_maillog_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailaddressdomain",
            name="kind",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("personal", "Personal"),
                    ("institutional", "Institutional"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
    ]
