# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-19 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0021_precookedemail'),
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi_batch_id', models.CharField(default='', max_length=40)),
                ('metadata_xml', models.TextField(blank=True, null=True)),
                ('deposition_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='first_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Publication'),
        ),
    ]
