# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-19 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20161019_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='issn',
            field=models.CharField(default='2542-4653', max_length=16),
        ),
    ]
