# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-22 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_journal_issn'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='authors_unregistered',
            field=models.ManyToManyField(blank=True, to='journals.UnregisteredAuthor'),
        ),
    ]
