# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-22 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_auto_20161122_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='first_author_unregistered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_author_unregistered', to='journals.UnregisteredAuthor'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors_unregistered',
            field=models.ManyToManyField(blank=True, related_name='authors_unregistered', to='journals.UnregisteredAuthor'),
        ),
    ]
