# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-23 05:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_auto_20161122_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='citedby',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
