# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_publication_citedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('number', 'in_volume')]),
        ),
    ]
