# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_auto_20170210_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together=set([('number', 'in_journal')]),
        ),
    ]
