# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='doi_string',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='doi_string',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volume',
            name='doi_string',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
