# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_auto_20170407_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='doi_string',
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(choices=[('SciPost Physics', 'SciPost Physics'), ('SciPostPhysLecture', 'SciPost Physics Lecture Notes'), ('SciPostPhysSel', 'SciPost Physics Select'), ('SciPostPhysProc', 'SciPost Physics Proceedings')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi_label',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
