# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0011_auto_20170407_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='doi_label',
            new_name='doi_string',
        ),
    ]
