# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-08 15:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0014_journal_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='doi_string',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+.[0-9]+.[0-9]+$', 'Only valid DOI expressions are allowed ([a-zA-Z]+.[0-9]+.[0-9]+).')]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='doi_string',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only valid DOI expressions are allowed ([a-zA-Z]+).')]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi_string',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+.[0-9]+.[0-9]+.[0-9]{3,}$', 'Only valid DOI expressions are allowed ([a-zA-Z]+.[0-9]+.[0-9]+.[0-9]{3,}).')]),
        ),
        migrations.AlterField(
            model_name='volume',
            name='doi_string',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+.[0-9]+$', 'Only valid DOI expressions are allowed ([a-zA-Z]+.[0-9]+).')]),
        ),
    ]
