# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0015_auto_20170408_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='doi_string',
            new_name='doi_label',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='doi_string',
            new_name='doi_label',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='doi_string',
            new_name='doi_label',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='doi_string',
            new_name='doi_label',
        ),
    ]
