# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0054_delete_newsitem'),
        ('journals', '0017_auto_20170515_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionevent',
            old_name='noted',
            new_name='noted_on',
        ),
        migrations.AddField(
            model_name='productionevent',
            name='noted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='scipost.Contributor'),
        ),
    ]
