# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0019_auto_20170515_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='journals.ProductionStream'),
        ),
        migrations.AlterField(
            model_name='productionstream',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='submissions.Submission'),
        ),
    ]
