# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0021_auto_20170517_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionevent',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionevent',
            name='noted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
