# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0022_auto_20170517_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionevent',
            name='noted_by',
        ),
        migrations.RemoveField(
            model_name='productionevent',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='productionstream',
            name='submission',
        ),
        migrations.DeleteModel(
            name='ProductionEvent',
        ),
        migrations.DeleteModel(
            name='ProductionStream',
        ),
    ]
