# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-08 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0023_auto_20170517_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='lastest_citedby_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
