# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-08 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0024_publication_lastest_citedby_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='lastest_citedby_update',
            new_name='latest_citedby_update',
        ),
    ]
