# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0025_auto_20170708_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='latest_crossref_deposit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='latest_metadata_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='metadata_xml_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
