# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-10 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0026_auto_20170708_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='metadata_xml_file',
        ),
        migrations.AddField(
            model_name='deposit',
            name='metadata_xml_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='deposit',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='timestamp',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposition_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
