# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-10 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0028_auto_20170710_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='latest_crossref_deposit',
        ),
    ]
