# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0029_remove_publication_latest_crossref_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='metadata_xml_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=''),
        ),
    ]
