# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0030_auto_20170710_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLOCKSSmetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_xml_file_CLOCKSS', models.FileField(blank=True, max_length=512, null=True, upload_to='')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Publication')),
            ],
        ),
    ]
