# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0031_clockssmetadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockssmetadata',
            options={'verbose_name': 'CLOCKSS metadata'},
        ),
    ]
