# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-08 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('partners', '0005_organization'),
        ('journals', '0032_authoraffiliation'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='publicationauthorstable',
        #     name='affiliations',
        #     field=models.ManyToManyField(blank=True, to='partners.Organization'),
        # ),
    ]
