# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 18:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0032_auto_20170711_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOAJDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(default='', max_length=40)),
                ('metadata_DOAJ', django.contrib.postgres.fields.jsonb.JSONField()),
                ('deposition_date', models.DateTimeField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('deposit_successful', models.NullBooleanField(default=None)),
            ],
            options={
                'verbose_name': 'DOAJ deposit',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='metadata_DOAJ',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doajdeposit',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.Publication'),
        ),
    ]
