# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0033_auto_20170711_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='cc_license',
            field=models.CharField(choices=[('CC BY 4.0', 'CC BY (4.0)'), ('CC BY-SA 4.0', 'CC BY-SA (4.0)'), ('CC BY-NC 4.0', 'CC BY-NC (4.0)')], default='CC BY 4.0', max_length=32),
        ),
    ]
