# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0034_publication_cc_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockssmetadata',
            name='publication',
        ),
        migrations.DeleteModel(
            name='CLOCKSSmetadata',
        ),
    ]
