# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 18:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0035_auto_20170714_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='metadata_DOAJ',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
