# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0036_auto_20170725_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='grants',
            field=models.ManyToManyField(blank=True, to='journals.Grant'),
        ),
    ]
