# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0037_auto_20170725_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='funder',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='grants',
        ),
        migrations.DeleteModel(
            name='Funder',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
    ]
