# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0001_initial'),
        ('journals', '0038_auto_20170725_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='grants',
            field=models.ManyToManyField(blank=True, to='funders.Grant'),
        ),
    ]
