# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0036_auto_20170725_2048'),
        ('journals', '0039_publication_grants'),
    ]

    operations = [
    ]
