# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-27 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0005_grant_further_details'),
        ('journals', '0040_merge_20170726_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='funders_generic',
            field=models.ManyToManyField(blank=True, to='funders.Funder'),
        ),
    ]
