# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('partners', '0017_auto_20180922_1603'),
        ('organizations', '0002_populate_from_partners_org'),
        ('journals', '0040_auto_20180922_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgpubfraction',
            old_name='org',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='publicationauthorstable',
            old_name='affs',
            new_name='affiliations',
        ),
        migrations.AlterUniqueTogether(
            name='orgpubfraction',
            unique_together=set([('organization', 'publication')]),
        ),
    ]
