# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0041_publication_funders_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doajdeposit',
            name='metadata_DOAJ_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=''),
        ),
    ]
