# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0044_publication_doideposit_needs_updating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='publications', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors_claims',
            field=models.ManyToManyField(blank=True, related_name='claimed_publications', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors_false_claims',
            field=models.ManyToManyField(blank=True, related_name='false_claimed_publications', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors_unregistered',
            field=models.ManyToManyField(blank=True, related_name='publications', to='journals.UnregisteredAuthor'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='first_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_author_publications', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='first_author_unregistered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_author_publications', to='journals.UnregisteredAuthor'),
        ),
    ]
