# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0047_auto_20171101_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(blank=True, default='2542-4653', max_length=16),
        ),
    ]
