# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0048_auto_20171101_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='funders_generic',
            field=models.ManyToManyField(blank=True, related_name='publications', to='funders.Funder'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='grants',
            field=models.ManyToManyField(blank=True, related_name='publications', to='funders.Grant'),
        ),
    ]
