# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0051_auto_20171102_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='institutes',
            new_name='institutions',
        ),
    ]
