# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0052_journal_refereeing_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregisteredauthor',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile'),
        ),
    ]
