# Generated by Django 2.1.8 on 2019-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0065_auto_20190522_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
