# Generated by Django 2.1.8 on 2019-09-22 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0071_remove_publication_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi_label',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z]+(.\\w+(.[0-9]+(.[0-9]{3,})?)?)?', 'Only valid DOI expressions are allowed: `[a-zA-Z]+(.\\w+(.[0-9]+(.[0-9]{3,})?)?)?`')]),
        ),
    ]
