# Generated by Django 2.2.11 on 2020-07-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0087_auto_20200506_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors_claims',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors_false_claims',
        ),
    ]
