MAIL_LIST_STATUS_ACTIVE = 'active'
MAIL_LIST_STATUS_REMOVED = 'removed'
MAIL_LIST_STATUS_DEACTIVATED = 'deactivated'
MAIL_LIST_STATUSES = (
    (MAIL_LIST_STATUS_ACTIVE, 'Active'),
    (MAIL_LIST_STATUS_REMOVED, 'Removed'),
    (MAIL_LIST_STATUS_DEACTIVATED, 'Deactivated'),
)
