# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theses', '0001_initial'),
        ('submissions', '0001_initial'),
        ('scipost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorshipclaim',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
        migrations.AddField(
            model_name='authorshipclaim',
            name='thesislink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theses.ThesisLink'),
        ),
        migrations.AddField(
            model_name='authorshipclaim',
            name='vetted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor'),
        ),
    ]
