# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0004_auto_20160415_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'default_permissions': ['add', 'view', 'change', 'delete']},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'default_permissions': ['add', 'view', 'change', 'delete']},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'default_permissions': ['add', 'view', 'change', 'delete']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'default_permissions': ['add', 'view', 'change', 'delete']},
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
