# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0006_auto_20160421_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('length', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=32)),
                ('added_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor')),
                ('graph', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scipost.Graph')),
            ],
        ),
        migrations.RemoveField(
            model_name='node',
            name='arcs_in',
        ),
        migrations.AddField(
            model_name='arc',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='scipost.Node'),
        ),
        migrations.AddField(
            model_name='arc',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='scipost.Node'),
        ),
    ]
