# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20160527_2215'),
        ('scipost', '0007_auto_20160515_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinvitation',
            name='cited_in_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
        migrations.AlterField(
            model_name='registrationinvitation',
            name='invitation_type',
            field=models.CharField(choices=[('F', 'Editorial Fellow'), ('C', 'Contributor'), ('R', 'Refereeing'), ('ci', 'cited')], default='C', max_length=2),
        ),
    ]
