# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-02 03:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0009_auto_20160604_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='specializations',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
