# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-13 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0021_remove_eicrecommendation_remarks_during_voting'),
        ('scipost', '0016_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.EICRecommendation'),
        ),
    ]
