# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0017_remark_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('headline', models.CharField(max_length=300)),
                ('blurb', models.TextField()),
                ('followup_link', models.URLField(blank=True, null=True)),
                ('followup_link_text', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
