# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-17 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0018_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='accepts_SciPost_emails',
            field=models.BooleanField(default=True, verbose_name='I accept to receive SciPost emails'),
        ),
    ]
