# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        ('scipost', '0019_contributor_accepts_scipost_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinvitation',
            name='cited_in_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journals.Publication'),
        ),
        migrations.AddField(
            model_name='registrationinvitation',
            name='date_last_reminded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationinvitation',
            name='nr_reminders',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrationinvitation',
            name='invitation_type',
            field=models.CharField(choices=[('F', 'Editorial Fellow'), ('C', 'Contributor'), ('R', 'Refereeing'), ('ci', 'cited in submission'), ('cp', 'cited in publication')], default='C', max_length=2),
        ),
    ]
