# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 17:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0020_auto_20160920_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecookedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=300)),
                ('email_text', models.TextField()),
                ('email_text_html', models.TextField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('emailed_to', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), blank=True, size=None)),
                ('date_last_used', models.DateField(default=django.utils.timezone.now)),
                ('deprecated', models.BooleanField(default=False)),
            ],
        ),
    ]
