# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0021_precookedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinvitation',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
