# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-12 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0022_registrationinvitation_declined'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPBMembershipAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Submitted', 'Request submitted by Partner'), ('Pending', 'Sent to Partner, response pending'), ('Signed', 'Signed by Partner'), ('Honoured', 'Honoured: payment of Partner received')], max_length=16)),
                ('date_requested', models.DateField()),
                ('start_date', models.DateField()),
                ('duration', models.DurationField(choices=[(datetime.timedelta(365), '1 year'), (datetime.timedelta(1095), '3 years'), (datetime.timedelta(1825), '5 years')])),
            ],
        ),
        migrations.CreateModel(
            name='SupportingPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('Int. Fund. Agency', 'International Funding Agency'), ('Nat. Fund. Agency', 'National Funding Agency'), ('Univ. Library', 'University Library'), ('Univ. Library. Consortium', 'University Library Consortium'), ('Foundation', 'Foundation'), ('Individual', 'Individual')], max_length=32)),
                ('status', models.CharField(choices=[('Prospective', 'Prospective'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=16)),
                ('institution', models.CharField(max_length=256)),
                ('institution_acronym', models.CharField(max_length=10)),
                ('institution_address', models.CharField(max_length=1000)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor')),
            ],
        ),
        migrations.AddField(
            model_name='spbmembershipagreement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scipost.SupportingPartner'),
        ),
    ]
