# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 05:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0023_auto_20161112_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingpartner',
            name='consortium_members',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spbmembershipagreement',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(365), '1 year'), (datetime.timedelta(730), '2 years'), (datetime.timedelta(1095), '3 years'), (datetime.timedelta(1460), '4 years'), (datetime.timedelta(1825), '5 years')]),
        ),
        migrations.AlterField(
            model_name='supportingpartner',
            name='partner_type',
            field=models.CharField(choices=[('Int. Fund. Agency', 'International Funding Agency'), ('Nat. Fund. Agency', 'National Funding Agency'), ('Nat. Library', 'National Library'), ('Univ. Library', 'University Library'), ('Res. Library', 'Research Library'), ('Consortium', 'Consortium'), ('Foundation', 'Foundation'), ('Individual', 'Individual')], max_length=32),
        ),
    ]
