# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0024_auto_20161117_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('institution', models.CharField(max_length=128)),
                ('subunit', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='spbmembershipagreement',
            name='offered_yearly_contribution',
            field=models.SmallIntegerField(default=0),
        ),
    ]
