# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0027_citationnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citationnotification',
            name='date_drafted',
        ),
    ]
