# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0028_auto_20161212_1931'),
        ('scipost', '0028_remove_citationnotification_date_drafted'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
    ]
