# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0029_remark_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.TextField()),
                ('motion', models.TextField()),
                ('date', models.DateField()),
                ('nr_A', models.PositiveIntegerField(default=0)),
                ('nr_N', models.PositiveIntegerField(default=0)),
                ('nr_D', models.PositiveIntegerField(default=0)),
                ('voting_deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='voting deadline')),
                ('accepted', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VGM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='motion',
            name='VGM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scipost.VGM'),
        ),
        migrations.AddField(
            model_name='motion',
            name='in_agreement',
            field=models.ManyToManyField(blank=True, related_name='in_agreement_with_motion', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='motion',
            name='in_disagreement',
            field=models.ManyToManyField(blank=True, related_name='in_disagreement_with_motion', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='motion',
            name='in_notsure',
            field=models.ManyToManyField(blank=True, related_name='in_notsure_with_motion', to='scipost.Contributor'),
        ),
        migrations.AddField(
            model_name='motion',
            name='put_forward_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scipost.Contributor'),
        ),
    ]
