# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0030_auto_20170118_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='motion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scipost.Motion'),
        ),
    ]
