# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0032_auto_20170121_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='VGM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scipost.VGM'),
        ),
    ]
