# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0033_nomination_vgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='category',
            field=models.CharField(choices=[('ByLawAmend', 'Amendments to by-laws'), ('Workflow', 'Editorial workflow improvements'), ('General', 'General')], default='General', max_length=10),
        ),
    ]
