# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0034_motion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgm',
            name='information',
            field=models.TextField(default=''),
        ),
    ]
