# Generated by Django 2.2.11 on 2020-07-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0035_auto_20191123_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorshipclaim',
            name='publication',
        ),
    ]
