# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0037_remark_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='webpage',
            field=models.URLField(default=''),
        ),
    ]
