# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0038_nomination_webpage'),
    ]

    operations = [
        # I'm in a vacuum state.
        # Please don't remove me though...
    ]
