# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0038_nomination_webpage'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='VGM',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='by',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='VGM',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='in_agreement',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='in_disagreement',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='in_notsure',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='put_forward_by',
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='VGM',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='by',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='in_agreement',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='in_disagreement',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='in_notsure',
        ),
        migrations.AlterField(
            model_name='remark',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualmeetings.Feedback'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='motion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualmeetings.Motion'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='nomination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualmeetings.Nomination'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Motion',
        ),
        migrations.DeleteModel(
            name='Nomination',
        ),
        migrations.DeleteModel(
            name='VGM',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
