# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0040_auto_20170317_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialCollegeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=10)),
                ('link', models.URLField(blank=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='scipost.EditorialCollege')),
            ],
        ),
    ]
