# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0041_editorialcollege_editorialcollegemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialcollege',
            name='discipline',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
