# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 21:37
from __future__ import unicode_literals

from django.db import migrations

from ..db.constants_migration_0043 import collegeMembers


def fill_editorial_college(apps, schema_editor):
    EditorialCollege = apps.get_model('scipost', 'EditorialCollege')
    EditorialMember = apps.get_model('scipost', 'EditorialCollegeMember')
    college, new = EditorialCollege.objects.get_or_create(discipline='Physics')
    for member in collegeMembers:
        EditorialMember.objects.get_or_create(discipline=college, **member)


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0042_auto_20170318_2119'),
    ]

    operations = [
        migrations.RunPython(fill_editorial_college),
    ]
