# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scipost.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0044_auto_20170319_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialCollegeFellow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_activity', scipost.db.fields.AutoDateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellows', to='scipost.EditorialCollege')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scipost.Contributor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='editorialcollegemember',
            name='college',
        ),
        migrations.DeleteModel(
            name='EditorialCollegeMember',
        ),
    ]
