# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0045_auto_20170319_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialcollegefellow',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editorialcollegefellow',
            name='until_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
