# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import scipost.models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0046_auto_20170319_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='vetted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(scipost.models.get_sentinel_user), related_name='contrib_vetted_by', to='scipost.Contributor'),
        ),
        migrations.AlterUniqueTogether(
            name='editorialcollegefellow',
            unique_together=set([('contributor', 'college', 'start_date', 'until_date')]),
        ),
    ]
