# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scipost.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0047_auto_20170319_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialCollegeFellowship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_activity', scipost.db.fields.AutoDateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('until_date', models.DateField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowships', to='scipost.EditorialCollege')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scipost.Contributor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='editorialcollegefellow',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='editorialcollegefellow',
            name='college',
        ),
        migrations.RemoveField(
            model_name='editorialcollegefellow',
            name='contributor',
        ),
        migrations.DeleteModel(
            name='EditorialCollegeFellow',
        ),
        migrations.AlterUniqueTogether(
            name='editorialcollegefellowship',
            unique_together=set([('contributor', 'college', 'start_date', 'until_date')]),
        ),
    ]
