# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0048_auto_20170320_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialcollegefellowship',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
