# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0049_editorialcollegefellowship_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='invitation_key',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationinvitation',
            name='cited_in_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_invitations', to='submissions.Submission'),
        ),
        migrations.AlterField(
            model_name='registrationinvitation',
            name='invitation_key',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationinvitation',
            name='personal_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
