# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0051_auto_20170504_1359'),
    ]

    database_operations = [
        migrations.AlterModelTable('Motion', 'virtualmeetings_motion'),
        migrations.AlterModelTable('Feedback', 'virtualmeetings_feedback'),
        migrations.AlterModelTable('Nomination', 'virtualmeetings_nomination'),
        migrations.AlterModelTable('VGM', 'virtualmeetings_vgm'),
        migrations.AlterField(
            model_name='motion',
            name='VGM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualmeetings.VGM'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='VGM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualmeetings.VGM'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='VGM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualmeetings.VGM'),
        ),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='VGM',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='by',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='VGM',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='in_agreement',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='in_disagreement',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='in_notsure',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='put_forward_by',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='VGM',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='by',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='in_agreement',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='in_disagreement',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='in_notsure',
        ),
        migrations.DeleteModel('Motion'),
        migrations.DeleteModel('Feedback'),
        migrations.DeleteModel('Nomination'),
        migrations.DeleteModel('VGM')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
