# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualmeetings', '0001_initial'),
        ('scipost', '0052_auto_20170504_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualmeetings.Feedback'),
        ),
        migrations.AddField(
            model_name='remark',
            name='motion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualmeetings.Motion'),
        ),
        migrations.AddField(
            model_name='remark',
            name='nomination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualmeetings.Nomination'),
        ),
    ]
