# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0054_delete_newsitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spbmembershipagreement',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='supportingpartner',
            name='contact_person',
        ),
        migrations.DeleteModel(
            name='SPBMembershipAgreement',
        ),
        migrations.DeleteModel(
            name='SupportingPartner',
        ),
    ]
