# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-23 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0055_auto_20170519_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='title',
            field=models.CharField(choices=[('PR', 'Prof.'), ('DR', 'Dr'), ('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms')], max_length=4),
        ),
        migrations.AlterField(
            model_name='draftinvitation',
            name='title',
            field=models.CharField(choices=[('PR', 'Prof.'), ('DR', 'Dr'), ('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms')], max_length=4),
        ),
        migrations.AlterField(
            model_name='registrationinvitation',
            name='title',
            field=models.CharField(choices=[('PR', 'Prof.'), ('DR', 'Dr'), ('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms')], max_length=4),
        ),
    ]
