# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-01 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0058_auto_20170624_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unavailabilityperiod',
            options={'ordering': ['-start']},
        ),
    ]
