# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-08 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0056_auto_20170618_2024'),
        ('scipost', '0059_auto_20170701_1356'),
    ]

    operations = [
    ]
