# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0059_auto_20170701_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='address',
            field=models.CharField(blank=True, max_length=1000, verbose_name='address'),
        ),
    ]
