# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-30 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0060_auto_20170726_1612'),
        ('scipost', '0060_merge_20170708_0941'),
    ]

    operations = [
    ]
