# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0061_merge_20170730_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='activation_key',
            new_name='_activation_key',
        ),
    ]
