# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0062_auto_20170815_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='_activation_key',
            new_name='activation_key',
        ),
        migrations.AlterField(
            model_name='remark',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='virtualmeetings.Feedback'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='motion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='virtualmeetings.Motion'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='nomination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='virtualmeetings.Nomination'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='submissions.EICRecommendation'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='submissions.Submission'),
        ),
        migrations.AlterField(
            model_name='unavailabilityperiod',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_periods', to='scipost.Contributor'),
        ),
    ]
