# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0044_publication_doideposit_needs_updating'),
        ('scipost', '0064_auto_20170909_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorshipclaim',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journals.Publication'),
        ),
    ]
