# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0002_affiliation_acronym'),
        ('scipost', '0065_authorshipclaim_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='_affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='affiliations.Institution'),
        ),
    ]
