# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0068_auto_20171101_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='affiliation',
            new_name='old_affiliation_fk',
        ),
    ]
