# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliations', '0006_auto_20171102_0843'),
        ('scipost', '0069_auto_20171102_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='old_affiliation_fk',
        ),
    ]
