# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scipost', '0071_auto_20171102_0858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AffiliationObject',
        ),
    ]
