# Generated by Django 2.2.11 on 2020-04-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0085_auto_20191017_0949'),
        ('series', '0003_collection_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='container_journals',
            field=models.ManyToManyField(blank=True, to='journals.Journal'),
        ),
    ]
