# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('production', '0028_auto_20171007_1311'),
    ]

    operations = []
