# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finances', '0002_auto_20171007_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worklog',
            old_name='target_object_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='worklog',
            old_name='target_content_type',
            new_name='content_type',
        ),
        migrations.AlterField(
            model_name='worklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
