# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20171007_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='contenttypes.ContentType'),
        ),
    ]
