# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20171007_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worklog',
            options={'ordering': ['-work_date', 'created']},
        ),
        migrations.AddField(
            model_name='worklog',
            name='log_type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
