# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-14 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import scipost.storage


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_auto_20190214_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(storage=scipost.storage.SecureFileStorage(), upload_to='UPLOADS/FINANCES/SUBSIDIES/ATTACHMENTS')),
                ('name', models.CharField(max_length=128)),
                ('publicly_visible', models.BooleanField(default=False)),
                ('subsidy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finances.Subsidy')),
            ],
        ),
    ]
