# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0003_petitionsignatory_organization"),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='petitionsignatory',
        #     old_name='organization',
        #     new_name='organization_tbd',
        # ),
    ]
