# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0006_repopulate_petsign_orgs'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='petitionsignatory',
        #     name='organization_tbd',
        # ),
    ]
