# Generated by Django 4.2.10 on 2024-03-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0021_enable_unaccent"),
        ("scipost", "0040_auto_20210310_2026"),
        ("petitions", "0009_auto_20210310_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petitionsignatory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="petitionsignatory",
            name="petition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="petitions.petition"
            ),
        ),
        migrations.AlterField(
            model_name="petitionsignatory",
            name="signatory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scipost.contributor",
            ),
        ),
    ]
