# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Relation",
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="topic",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="ontology.Tag"),
        ),
    ]
