# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0002_auto_20181027_1748"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="tags",
            field=models.ManyToManyField(blank=True, to="ontology.Tag"),
        ),
    ]
