# Generated by Django 3.2.16 on 2023-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0007_Branch_Field_Specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='specialties', to='ontology.Topic'),
        ),
    ]
