# Generated by Django 5.0.12 on 2025-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0010_topicinterest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicinterest",
            name="weight",
            field=models.FloatField(
                default=1.0,
                help_text="Relative interest in the range [-1, 1], e.g. 0.4 or -0.3. A weight of (0/-1/1) means (no/dis/-) interest.",
            ),
        ),
    ]
