# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='emailed',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='public',
        ),
        migrations.AddField(
            model_name='notification',
            name='internal_type',
            field=models.CharField(blank=True, choices=[('referee_task_deadline', 'Refereeing Task is approaching its deadline'), ('referee_task_overdue', 'Refereeing Task is overdue')], max_length=255),
        ),
    ]
