# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
