# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='internal_type',
            field=models.CharField(blank=True, choices=[('referee_task_deadline', 'Refereeing Task is approaching its deadline'), ('referee_task_overdue', 'Refereeing Task is overdue'), ('report_unfinished', 'Report is in draft')], max_length=255),
        ),
    ]
