# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180819_1343'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='notification',
        #     name='url_code',
        #     field=models.CharField(blank=True, max_length=255),
        # ),
    ]
