# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20171021_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pseudo_unread',
            field=models.BooleanField(default=True),
        ),
    ]
