# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20171021_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeActors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
