# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_fakeactors'),
        ('notifications', '0003_notification_pseudo_unread'),
    ]

    operations = [
    ]
