# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-07 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_url_code'),
        ('notifications', '0003_notification_url_code'),
    ]

    operations = [
    ]
