# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_merge_20171103_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='unread_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
