# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20171105_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='unread_datetime',
        ),
    ]
