# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0025_auto_20180520_1430"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preprint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scipost_preprint_identifier",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("identifier_w_vn_nr", models.CharField(max_length=25)),
                ("identifier_wo_vn_nr", models.CharField(max_length=25)),
                ("vn_nr", models.PositiveSmallIntegerField(default=1)),
                ("url", models.URLField()),
                (
                    "_file",
                    models.FileField(
                        blank=True, max_length=200, upload_to="UPLOADS/PREPRINTS/%Y/%m/"
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submissions.Submission",
                    ),
                ),
            ],
        ),
    ]
