# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("preprints", "0002_auto_20180610_2014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preprint",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preprint",
                to="submissions.Submission",
            ),
        ),
    ]
