# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_thesislink_subject_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesislink',
            name='specialization',
        ),
    ]
