# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_remove_thesislink_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesislink',
            name='domain',
            field=models.CharField(choices=[('E', 'Experimental'), ('T', 'Theoretical'), ('C', 'Computational'), ('ET', 'Exp. & Theor.'), ('EC', 'Exp. & Comp.'), ('TC', 'Theor. & Comp.'), ('ETC', 'Exp., Theor. & Comp.')], max_length=3),
        ),
    ]
