# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0006_auto_20161219_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesislink',
            name='supervisor',
            field=models.CharField(max_length=1000),
        ),
    ]
