# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0008_auto_20170909_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesislink',
            name='author_as_cont',
            field=models.ManyToManyField(blank=True, related_name='theses', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='thesislink',
            name='author_claims',
            field=models.ManyToManyField(blank=True, related_name='claimed_theses', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='thesislink',
            name='author_false_claims',
            field=models.ManyToManyField(blank=True, related_name='false_claimed_theses', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='thesislink',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_theses', to='scipost.Contributor'),
        ),
        migrations.AlterField(
            model_name='thesislink',
            name='supervisor_as_cont',
            field=models.ManyToManyField(blank=True, related_name='supervised_theses', to='scipost.Contributor', verbose_name='supervisor(s)'),
        ),
    ]
